### ISSUE TITLE
Integrate EPA Crosswalk into PUDL

### ISSUE THREAD

**Issue by TrentonBush** [catalyst-cooperative/pudl#1123]
#### Context:

We did an initial integration with a WIP version of the EPA crosswalk in issue #822. Now that the [full version](https://www.epa.gov/airmarkets/power-sector-data-crosswalk) has been released, we can fully integrate it into PUDL.

Current integration is in:
* src/pudl/glue/eia_epacems.py
* bypassed in src/pudl/output/epacems.py
* run in src/pudl/etl.py:_add_eia_epacems_crosswalk

#### Steps:

- [x] Include raw source download in pudl-scrapers, including checking for new releases # 15 in the pudl-scrapers repo
- [ ] Include in Zenodo archive / Docker images, remove from package resources csv # 12 in the pudl-zenodo-storage repo
- [ ] Update processing currently in pudl/glue/eia_epacems.py, paying particular attention to which columns should be used as IDs (see next item)
- [ ] Implement pudl/transform/epacems.py:harmonize_eia_epa_orispl. This may have been done by the EPA already, see EPA docs, particularly the column MOD_EIA_PLANT_ID
- [ ] Add crosswalk to PUDL db and CEMS output table

#### Questions: 
- Should these glue files live in their own glue directory (as they currently do) or should they get extracted and transformed like the rest of the data that gets integrated into the PUDL db?

**Comment by zaneselvans** [comment]
Should probably consolidate with #843

**Comment by zaneselvans** [comment]
@TrentonBush was far more involved in this original work than I was, so for technical questions as to how to use this crosswalk information and integrate it with other data I think he's the main resource.

This is somewhere between being a new dataset, and being "glue" but I think we want to treat it more like a dataset -- there's a raw input from the EPA repo (that will be available in the datastore) and we need to perform some operations on it before it's ready to be loaded into the PUDL DB. We'll have FK relationships between that new table and the EPA CEMS / EIA tables. 

However, because the EPA CEMS doesn't get loaded into the DB, those FK relationships won't be checked automatically. Somehow we need to ensure that they're all valid. I imagine this will happen somewhere in the crosswalk ETL process, but I don't know what the direction of the dependencies is.

In the fullness of time, I could see it making sense to defer the crosswalk ETL until after the main DB and the EPA CEMS data have been processed, and then with access to both of those (interim) outputs, generate and load our version of the crosswalk into the DB. But that's something that won't happen until we've got the DAG set up.
