### ISSUE TITLE
Integrate EIA860 EnviroAssoc and EnviroEquip (Schedules 6.1 & 6.2)

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1162]
The EIA 860 reports data about what environmental quality control equipment is installed on what generators, but we haven't yet integrated it into PUDL. Bring it in!

Scope: Tables are extracted and transformed, and ready to be harvested along with 923 environmental data. See #3365 for harvesting, which is out of scope for this issue.

### Environmental Associations (Schedule 6.1)
`6_1_EnviroAssocYyyyy` – Contains association tables between boilers and control equipment, and information on equipment
* The Boiler Cooling tab shows associations between cooling equipment and boilers;
* The Boiler Mercury tab shows associations between mercury control equipment and boilers;
* The Boiler NOx tab shows associations between nitrogen oxide control equipment and boilers;
* The Boiler PM tab shows associations between particulate matter control equipment and boilers;
* The Boiler SO2 tab shows associations between sulfur dioxide control equipment and boilers;
* The Boiler Stack Flue tab shows associations between boilers, stacks and flues;
* The Emissions Control Equipment tab contains information about different pieces control equipment (cost, etc.)

### Environmental Equipment (Schedule 6.2)
`6_2_EnviroEquipYyyyy` – Contains environmental equipment data for the surveyed generators.
* The Emission Standards & Strategies tab shows boiler data as collected on Schedule 6, Part B of the Form EIA-860;
* The Boiler Info & Design Parameters tab shows boiler data as collected on Schedule 6, Part C;
* The Cooling tab shows cooling system data as collected on Schedule 6, Part D;
* The FGP tab shows FGP data as collected on Schedule 6, Part E;
* The FGD tab shows FGD data as collected on Schedule 6, Part F; and
* The StackFlue tab shows stack and flue data as collected on Schedule 6, Part G.

Complications to consider:
- m:m boiler:equipment relationships - how do we want to create well-defined tables?

```[tasklist]
### Tasks
- [ ] #2281
- [ ] #2305
- [ ] #2366
- [ ] #2375
- [ ] #2338
- [ ] Transform FGP table and harmonize with boiler strategy code columns in `boilers_eia860`
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3394
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3395
- [ ] Transform EIA 860 StackFlue table
```
