### ISSUE TITLE
Nightly Data Builds

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1177]
# Description
Automatically run the full ETL pipeline and data validation process under predefined circumstances (e.g. every night whenever new commits have been made to the `dev` or `main` branches). If the process completes successfully, deposit the outputs in cloud storage for distribution.

# Motivation
We only run the full ETL and data validation process rarely, typically after making large changes, integrating new data, or in the lead up to a release of some kind. This means many bugs aren't identified until long after they were introduced. This makes our software / data less reliable, reduces our productivity, and means that our officially released data is often stale.
* Do exhaustive testing (processing all years of all datasets) much more frequently, so that we catch bugs faster and more reliably.
* Make it easier to track down and fix bugs, since we discover them immediately while we still understand the context, and while there is a limited set of changes that they could be related to.
* Ensure that we are using data products in development that correspond to the code we are working with in development.
* Generate complete data products more frequently so that users have access to the most up to date data.
* Enable the automatic update and distribution of available data products for users.

# Tasks
* [x] #1601
* [x] #1605
* [x] #1606
* [x] #1603 
* [x] #1604 
* [x] #1607
* [x] Figure out how to deploy a Docker container to GCP and make it run (what will it run on? VMs don't seem quite meant for this, but we had wanted to get it running on a beefy single core.) [Google tutorial](https://github.com/google-github-actions/setup-gcloud/blob/main/example-workflows/gce/.github/workflows/gce.yaml) on how to deploy the container to GCE via Github Action.
* [ ] Figure out how to automatically trigger that deployment based on a GitHub event (push, PR, merge, etc.)
* [x] Figure out how to capture the logs from the Docker container somewhere persistent for later analysis.

# In Scope
* Automate running the full ETL (all years, all data sources) and output the FERC1 SQLite DB, PUDL SQLite DB, Census DP1 SQLite DB, and EPA CEMS Parquet dataset.
* Run all the Tox tests, including the full integration tests, and post-ETL data validation routines. 
* Determine the conditions under which to trigger a build (e.g. nightly if changes have been made to `dev` or `main`)
* Triggering the build on GCP using GitHub Actions, including starting up and shutting down the instance.
* Write the build logs to a location that will persist after we shut down the instance so we can see what went happened.
* Send notification of build outcome via Slack & Email.
* Generate test coverage report based on the full ETL, test, and validation process.
* Define a naming convention for the outputs (by branch, tag, commit, etc.)
* Enable manual triggering of a data build for a given branch, tag, or commit.
* Estimate of the cost of doing a full data build so we can budget appropriately and decide how many builds we want to be doing.
* Enable a lifecycle data storage policy for older non-release outputs. (e.g. keep the most recent `dev` and `main` builds regardless of how old they are, but delete any other non-release build after 30 days).

# Out of Scope
* Creation of any new data validations or integration tests.
* Integration of denormalized database views or new derived analysis tables into the outputs.
* https://github.com/catalyst-cooperative/pudl-catalog/issues/2
* Distribution of the outputs beyond dropping them in an appropriately named cloud storage resource.
* Implementation of distributed ETL using Dask+Kubernetes
