### ISSUE TITLE
Archive targeted Sloan grant data sets

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1412]
In order to avoid panic when websites remove their data we are interested in integrating, we should archive datasets as soon as we know we want to integrate them. 

There are a handful of datasets we want to integrate but haven't archived yet. 

- [x] #209 / catalyst-cooperative/pudl-archiver#51
- [x] #297 / catalyst-cooperative/pudl-archiver#52
- [x] #1413 / catalyst-cooperative/pudl-archiver#50
- [x] #1415 / catalyst-cooperative/pudl-archiver#49
- [x] catalyst-cooperative/pudl-archiver#31 / catalyst-cooperative/pudl-archiver#43

These datasets are listed in our [Future Datasets documentation](https://catalystcoop-pudl.readthedocs.io/en/dev/data_sources/wip_future.html#phmsa-natural-gas-pipelines) and our [Sloan New Data Plan](https://docs.google.com/document/d/1q9J49sDbwFNsbfk31p_sU0dSKiyq5TiO/edit#heading=h.gjdgxs).

**Comment by zaneselvans** [comment]
Another legacy VFP FERC dataset we should grab for posterity is the [FERC Form 60](https://www.ferc.gov/filing-forms/service-companies-filing-forms/Form-60-Historical-VFP-Data). Top secret unlisted download page:

https://www.ferc.gov/filing-forms/service-companies-filing-forms/Form-60-Historical-VFP-Data

**Comment by e-belfer** [comment]
With the exception of pre-2013 FERC EQR data, I think this is a closed epic.
