### ISSUE TITLE
Build CCAI output layer preprocessor function for entity matching

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/pudl#1452]
Start getting more of the CCAI stuff integrated into PUDL or at least prepare a structure so that when there are labeling functions that work they can be easily integrated into PUDL.

[EIA Plant Part List Column Descriptions](https://docs.google.com/spreadsheets/d/1AnjLlgeB-jr9iUtoRcLCNtXuydvFNIbDtDHzxJl6unM/edit#gid=0)

#### Tasks

- [x] Pare down the columns in the DFs we hand off to Chu lab - remove columns that are definitely not relevant in entity matching
 - See list below
- [ ] Construct new columns in EIA data
  - [x] `utilty_name_eia`
  - [ ] `construction_year`
  - [ ] `installation_year`
- [ ] (From weekly call notes) Add reference to the FERC 1 plant ID assignment in labeling column doc
- [ ] Start building and integrating preprocessor function - where does this go in PPL generation? - add to output layer
- [ ] Learn how adding attributes to PPL works
  - [ ] can we make CCAI specific outputs?

#### EIA Plant Part List
**Not sure if I should keep**
- generator_id
- operational_status_pudl
- ownership
- plant_id_pudl

**Columns to add/make**
- utility_name_eia - can be joined in with utility_id_eia and used to match with utility_name_ferc
- installation_year - needs to be refined/edited, see spreadsheet, can be derived from retirement_date
 - then take out retirement_date?
- construction_year - can be derived from retirement_date
