### ISSUE TITLE
Rework data source documentation to rely on metadata

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/pudl#1454]
With the new Metadata structure in place we can make our data source documentation more reliable and consistent by having it rely on the `DataSource` metadata class. 

#### Tasks

- [x] Check out what documentation already exists for Data Sources - is there an existing template for it?
 - Currently in static RSTs - generate from templates
 - Make into one big RST file with index links to sections? - I don't think you can link to sections not files with a TOC in `index.rst`
- Create a bunch of different templates?
 - Alternatively beef up `DataSource` class with text like Notable Irregularities and Background and make one template that generates different RST files
- [x] Simplest method: create a bunch of different templates that generate separate RST files
- [x] Create `to_rst` method in `DataSource` class
- [x] Add onto `metadata_to_rst` in Sphinx config file (`docs/conf.py`)
- [x] Add updated data source doc format to index pages/final fixes to how they look in docs

### Questions
- include EIA 861m?
- there are a bunch of sources in `sources.py` but still in `wip_future.rst`, should these sources have templates created for them now since they are in sources.py?
