### ISSUE TITLE
Create a local filesystem EPA CEMS Intake catalog by hand

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1493]
As a first step toward publishing our larger datasets in a cloud-optimized, versioned form, create a local EPA CEMS intake catalog by hand.
* The catalog should include basic metadata about the dataset so we can understand what kind of metadata we need to compile and how to format it in general, but it doesn't need to include everything we'll eventually want to publish.
* We should understand how to set up the Intake Catalog metadata such that the year/state partitions are individually accessible through the Intake API.

### Tasks
* [ ] Understand the metadata format required to create a valid Intake catalog for Parquet data. Use the [Carbon Plan Intake catalogs](https://github.com/carbonplan/data/tree/main/carbonplan_data/catalogs) as an example.
* [ ] Create a catalog for the year-state partitioned Parquet dataset stored on the local filesystem.
* [ ] Allow the user to request either a `pandas` or a `dask` dataframe from the catalog.
* [ ] Demonstrate that the local catalog can be accessed simply from within a local Jupyter notebook.
