### ISSUE TITLE
Adapt Parquet partitions for use with Intake

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1495]
# Goals for our EPA CEMS Intake Catalog
* Allow users to select just the years and states that they need, without waiting for the entire data set to be scanned or downloaded.
* Allow efficient local filesystem caching of the remote data, so that users don't have to download 5GB all at once, and so nobody has to pay unnecessary data egress fees.
* Ensure that parquet file names are human legible, machine readable, and compatible many different filesystems and parquet access methods.
* Allow the whole EPA CEMS data set to be processed in less than 10 min on GCP.
* Enable distributed creation of the parquet outputs, avoiding concurrent writes to the same files from different workers.

# Problems
* [x] Currently our EPA CEMS output creates a Hive partitioned Apache Parquet data set, hierarchically organized first by year and then by state.
* [x] The automatic Hive partitioning results in incomprehensible hash values for filenames.
* [x] The filenames change from run to run, meaning it's easy to accidentally write additional copies of the data into the same filesystem hierarchy without realizing it instead of overwriting a given chunk of data.
* [x] Hive partitioning also introduces non-standard characters (`=`) into the filesystem paths, removes the `state` and `year` columns from the dataframes, and requires that those columns be categorical (which makes sense for `state`, but less so for `year`).
* [x] The `intake_parquet` library doesn't understand how to deal with hierarchical directory-based partitioning.
* [x] The emissions mass & rate measurement method columns are showing up as `string` types, rather than `category` when we read out of the parquet data set (at least, as I've now re-written it using `ParquetWriter`). This ends up doubling the size of the data set in memory (fixed by #1563).
* `intake_parquet` doesn't seem to work well with a directory full of parquet files either.  I've tried several different ways of specifying `urlpath` with the following results:
  * `{{ env(INTAKE_PATH) }}/epacems-year-state.parquet` (monolithic file) -- selection of subsets of data using filters is fast, and having one file is simple, but this would prevent efficient local file caching (the whole 5GB would have to be downloaded)
  * `{{ env(INTAKE_PATH) }}/epacems-year-state/epacems*.parquet` (individual state-year files) -- it seems to scan all of the files without using the filters + metadata to avoid looking at files which cannot possibly contain the requested data. Reading the same data (1 year of CO) takes 10x as long as with a monolithic file. But this would work well for per-file caching.
  * `{{ env(INTAKE_PATH) }}/epacems-year-state/` (directory based) -- doesn't work at all. `intake_parquet` seems to require paths to specific files, even though dask and pandas are happy to look at a whole directory filled with parquet files.

# Design Choices:
* **When processing the EPA CEMS data, give each worker 1 year of data.** This will keep all of the work units about the same size and reduce the overhead associated with distributing tasks. Each year of data takes a couple of minutes to process.
* **Output a single state-year of data in each parquet file.** Store the files in a single directory with names that reflect what state-year they contain. This arrangement can be read automatically by pandas, dask, and Intake, and will allow us to do efficient per-file caching. We'll avoid having different workers trying to write to the same file.

# Tasks
* [x] Apply pudl dtypes to the individual monthly dataframes before annual concatenation to try and address #1126 
* [x] Get rid of the nested generators in the EPA CEMS ETL -- do the iteration at the top level in the ETL module and run each year-state through the whole ETL process before moving on to the next chunk of work.
* [x] Modify EPA CEMS ETL to output a single directory of files named `epacems-YYYY-SS.parquet` (where `YYYY` is the four digit year, and `SS` is the two letter state abbreviation). Use ParquetWriter instead of `pq.write_dataset()`
* [x] Ensure that all the columns have the specified data types when we read them back out of the new parquet files (esp. integer years, categorical states, and categorical measurement codes. Only a couple of ID columns should end up being `string` dtypes).

**Comment by zaneselvans** [comment]
Duplicate of #1012

**Comment by zaneselvans** [comment]
Remaining tasks identified in this issue are being integrated into Epic #1564
