### ISSUE TITLE
Update plant part list aggregation to accommodate 1:m FERC-EIA matches

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1555]
# Problem Description

The Plant Part List (PPL) shows EIA generators at a variety of useful aggregations.

Part of the role of the PPL is to help connect EIA records with FERC records that might be reported at different aggregations. Most of the time, pre-defined aggregations such as plant, unit, primemover, etc. are good enough, but occasionally there are instances where FERC records are comprised of a unique aggregation of EIA records not currently represented in the PPL.

This becomes apparent when you're going through the programmatically generated overrides sheet for a given utility subset and you notice that a FERC does not match any one of the existing PPL records, but rather a combination of two or more. When this is the case, we need a way to fabricate a new PPL record that corresponds to that FERC record so we can more accurately map the two datasets.

# The Plan

The majority of these changes will happen in the `plant_parts_eia.py` module in the pudl repo:

- [x] Create a csv containing all of the 1:m matches found in the manual validation of FERC-EIA matches. Add this as a function in `ferc1_eia_train.py`, taking training data and appending any multiple matches to a .csv that lives in `pudl.package_data.glue` #2516 

Write a single function in the MakePlantParts class at the end of the plant_parts_eia table generator (either before or after validation) that does the following: 

- [x] Use Katie/Christina's `match_to_single_pant_part()` function to get the "m" component of the 1:m records at the generator level. #2429 
- [x] Creates a new column in the mega gen table called **`ferc1_generator_agg_id`** that gives a unique id to all the generator records identified above that should be used to create a single new PPL record (to match FERC). #2429 
- [x] Add **`ferc1_generator_agg_id`** column to the `PLANT_PARTS` dict to create a new PPL aggregation called **match_ferc1** specific to these wonky FERC records #2429 
- [x] Update plant_parts_eia fields and metadata to incorporate new column into final version of PPL, to enable tracing of which records are getting aggregated. #2429 

Then, update the training data to refer to these new records:
- [x] Replace existing FERC-EIA match with match to new aggregated plant ID in training data

# Decision Points
- At what stage should the combined plant part ID get matched with FERC data? --> Discussed in #2429 , decision made to integrate in `prep_train_connections()`
