### ISSUE TITLE
Deploy PUDL Docker image to GCE

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1611]
Zane has successfully dockerized the PUDL ETL (#1605, #1606, #1610).  I tested building and deploying an image to GCE via Github actions #1603. Time to put the two together! Deploy the PUDL container to a GCE VM. 

## TODO:
- [x] Create service accounts for action and VM.
- [x] Create a VM instance for PUDL to run on. Associate with a service account.
- [x] Add gcloud update container step to docker-build-push.
- [x] Set env vars
- [ ] Mount volumes

## Things to consider
- [x] The docker-build-push action pushes to docker hub but I tested the deployment using Google Artifact Registry. How can we deploy an image from docker hub? Use `docker.io/catalystcoop/pudl-etl:gce-deploy` url.
- [x] Zane's been using a docker-compose.yml to specify the container configuration. Container Optimized VMs aren't very docker-compose friendly. What is the best way to specify container configuration for CO VMs? Seems like you configure the container via the VM settings.
    - [x] [How to mount volumes](https://cloud.google.com/compute/docs/containers/configuring-options-to-run-containers#mounting_a_host_directory_as_a_data_volume)?
    - [x] [Set env vars](https://cloud.google.com/compute/docs/containers/configuring-options-to-run-containers#setting_environment_variables)?

**Comment by bendnorman** [comment]
The `pudl_etl.sh` script is running inside a docker container on a VM instance! The ETL finishes but there is no way to view the outputs because I haven't got volume mounting working. I'm running into permissions issues because when I add volume mounts, the pudl_in and pudl_out directories on the host are created as root and the `catalyst` user in the dockerfile does not have permissions to the `pudl_in` and `pudl_out` directories. I'm going to pause on the volume mounting issue because I think once our inputs and outputs are connect to cloud buckets there won't be a need for mounting volumes on the VM disk. 

Changing the default image command was a pain in the butt. Each argument needs a separate `--container-arg` flag. The final gcloud deploy command:

```bash
gcloud compute instances update-container "$GCE_INSTANCE" \
            --zone "$GCE_INSTANCE_ZONE" \
            --container-image "docker.io/catalystcoop/pudl-etl:${{ needs.push_to_registry.steps.docker_metadata.outputs.tags }}" \
            --container-command "conda" \
            --container-arg="run" \
            --container-arg="--no-capture-output" \
            --container-arg="-p" \
            --container-arg="/home/catalyst/env" \
            --container-arg="bash" \
            --container-arg="./docker/pudl_etl.sh" \
            --container-env-file="./docker/.env" \
```

We could also just replace the unit test command in the dockerfile with the full etl bash script command.

Here are some helpful resources when working with Container Optimized VMs:
- [How to deploy container on VMs](https://cloud.google.com/compute/docs/containers/deploying-containers#prepare).
- [How to configure the containers.](https://cloud.google.com/compute/docs/containers/configuring-options-to-run-containers#setting_environment_variables)
- [`gcloud compute instance update-container` documentation](https://cloud.google.com/sdk/gcloud/reference/compute/instances/update-container#--container-mount-host-path).
- [Container Optimized VM Disk and file system overview](https://cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem).

```
sudo journalctl -r -u konlet-startup
```
Command for viewing container startup logs.

**Comment by bendnorman** [comment]
I don't think `gcloud compute instances update-container` restarts the container restarts if there are dangling containers that use the same image. I ran the image a couple of times via ssh without the --rm tag. I made a change to `pudl_etl.sh` but it wasn't reflected on the VM. I tried to delete the image via ssh but it told me a container was still using the image. I deleted all of the containers using the image and the image itself. I ran the `gcloud compute instances update-container` command and the new changes we reflected. 

This isn't a bug just something to be aware of.
