### ISSUE TITLE
Deploy Usage metrics dashboard

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1652]
We have set up a [usage-metrics](https://github.com/catalyst-cooperative/pudl-usage-metrics) etl using dagster which processes data locally and writes to a sqlite db. We'd like to update the data weekly and view a dashboard with relevant metrics. This will require:

- [ ] Create a BigQuery dagster resource so we can load data to bigquery
- [ ] Set up a github action that processes a partition of data each week. 
- [ ] Create a metabase or preset dashboard and link to the usage metrics in BigQuery.
