### ISSUE TITLE
Transform FERC1 Plant Tables

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1801]
The FERC1 plant tables are already in the PUDL DB. We just need to harmonize the DBF version and the XBRL version of the following tables: 

- [x] `f1_steam` (in pudl db)
- [x] `f1_hydro` (in pudl db)
- [x] `f1_pumped_storage` (in pudl db)
- [x] `f1_gnrt_plant` (in pudl db)

See [this spreadsheet](https://docs.google.com/spreadsheets/d/1OiP38SdHD9AYq6Whzmqioc850YiczBUDLVyG9Mf9_Uk/edit#gid=1423737513) for all tables and priorities
