### ISSUE TITLE
Transform FERC1 Balance Sheet Tables

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1804]
None of the balance sheet tables are currently in PUDL. We'll need to write new transforms for the DBF and XBRL files.

- [x] `f1_comp_balance_db` (not in pudl db)
- [x] `f1_utltyplnt_smmry` (not in pudl db)
- [x] `f1_plant_in_srvce` (not in pudl db)
- [x] `f1_accumdepr_prvsn` (not in pudl db)

See [this spreadsheet ](https://docs.google.com/spreadsheets/d/1OiP38SdHD9AYq6Whzmqioc850YiczBUDLVyG9Mf9_Uk/edit#gid=1423737513)for all tables and priorities
