### ISSUE TITLE
Transform `plant_in_srvce` xbrl + dbf

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1807]
The Plant in Service table is the only "row mapped" table that we've already pulled into PUDL. Even though it's not the highest priority of this type of table, we want tackle it first so we can learn from it, and adapt the new transform process to accommodate it, since there are lots of other tables like this.

* The DBF data is row-oriented, with each row number pertaining to a different FERC account number, or to subtotals and totals of various groups of related FERC accounts, and different columns representing starting & ending balances, additions, transfers, subtractions, etc.
* The XBRL data is column-oriented, with different columns representing different FERC account numbers and the additions/retirements/transfers/etc.  This results in more than 400 columns.
* We've decided to go with the "tidy" or "long" format for these tables, with each column representing a different quantity, and the rows containing identifying information about that quantity.

For the `plant_in_service` table, this means we'll end up with 6 columns, which happen to correspond to the structure that we find int he DBF tables, but with static IDs rather than annually varying row numbers for the different FERC Accounts. The columns will be:

* `starting_balance` (XBRL instant)
* `additions` (XBRL duration)
* `retirements` (XBRL duration)
* `adjustments` (XBRL duration)
* `transfers` (XBRL duration)
* `ending_balance` (XBRL instant)

## XBRL Taxonomy Metadata
To effectively aggregate the values in the above columns, we need some additional metadata, available from the XBRL Taxonomy:
* The groupings of FERC accounts are stable and applied uniformly in many contexts because they are important for filing taxes appropriately. We want to preserve as much of that structure as possible so that both the individual accounts, and their meaningful groupings can be analyzed.
* We need to take care that the sign convention for different rows/columns are propagated and standardized. E.g. the `retirements` column is a `credit` while all the others are `debit`, but the convention flips in rows that represent sales of equipment rather than purchases.

## Table Notes
```py
pis_dbf = pd.read_sql("f1_plant_in_srvce", ferc1_engine)
pis_xbrl_duration = pd.read_sql("electric_plant_in_service_204_duration", ferc1_xbrl_engine)
pis_xbrl_instant = pd.read_sql("electric_plant_in_service_204_instant", ferc1_xbrl_engine)
```

* DBF has start/end balance + add/retire/adjust/transfer, as rows w/ labels accessible in the `f1_row_lit_tbl`
* XBRL data has legible column names but no account numbers (though they are available in the XBRL taxonomy)
* XBRL Instant has one number for each account or grouping. Turns out these are "end of last year" and "end of this year" balances, which we can transform into `starting_balance` and `ending_balance` in the current year. However we have to do some reshaping of the instant table to make this work (turning 2 years of 1 group of columns into 1 year of 2 groups of columns).
* XBRL Duration table has has columns w/ legible names but no FERC Acct numbers.
* There are almost 500 XBRL columns: ~100 different variables, with 6 variables reported for each one.
* DBF data has a mix of header, subheader, total, subtotal, FERC account and a few other numerical values.
* XBRL seems to have clean naming, but names alone can't be used to group the categories.
* XBRL has FERC accounts in the metadata.
* Seems like it makes sense to adopt the XBRL column names as the new labels for the old (and variable) DBF row numbers.

## Tasks
A bespoke reshaping transformation has been implemented via #2025 but we need some additional metadata to enable all the aggregations, which @cmgosnell has communicated is the next priority for RMI.
* [x] Read XBRL taxonomy JSON into a dataframe, retaining the name, account, calculation, and balance columns.
* [x] Normalize the account column to contain a simple string value.
* [x] Figure out how to select just the relevant XBRL values for the `plant_in_service` table from the larger dataframe
* [x] Figure out how to / whether we can reshape the wide-format categories into a table of metadata that applies uniformly across the 6 columns we are retaining. **yes we can**
* [x] Implement renaming of instant & duration XBRL tables so they follow a programmatically usable naming convention.
* [x] Compile column sign conventions in a dictionary.
* [x] Fix dev notebook to work with all the renamed columns.
* [x] Fix the overwhelming warnings resulting from `column_rename()`
* [x] Fix overwhelming warnings from duplicat `record_id` in reshaped tables.
* [x] Fix bad XBRL multi-index construction that is scrambling all the reported values.
* [x] Pull draft metadata extraction functions into module & apply sign conventions in `transform_main()`
* [x] Split `merge_metadata()` and `apply_sign_conventions()` into two methods
* [x] Simplify / clarify calculation empty list mess.
* [x] Use just one name for `xbrl_metadata_json`.

### Later tasks
* [ ] Get @zschira to add table name as a top level of nesting or an attribute so only a given table's metadata can be selected from the JSON, without needing to know what all columns appear in that table independently.
* [ ] Have the transformer take the table-specific JSON object as an input, and store that, to be normalized and used at the appropriate point in the transform... and also potentially returned as an output so we can load it into the DB.
* [ ] Define a database table for the transformed metadata so we can store it in a normalized way. May need to define a separate metadata transformation process either inside or outside of the table transformers.
* [ ] Clean up the tangle of different `ferc_account_*` fields and build a rational structure to hold that information in one place.
* [ ] Build a draft XBRL category metadata table that includes FERC accounts and sign conventions.
* [ ] Manually add aggregation categories to the metadata table based on calculations in XBRL taxonomy.
* [ ] Verify that aggregations result in the reported values.
* [ ] #2066
* [ ] Construct an an aggregation tree from the reported calculations, and use that for aggregating in non-tabular ways.

**Comment by jrea-rmi** [comment]
I'll be following this. I need to review the PUDL output version of this table, compare to the version we made for the Utility Transition Hub for combining with the balance sheet, and may have suggested edits.

**Comment by zaneselvans** [comment]
Working on applying the debit/credit sign conventions to the reshaped data, and noticing that the XBRL data seem to have a substantially higher proportion of negative numbers in the `retirements` column than the DBF data did. Do we think that's real? Or a potential data entry error? Have you seen this in your wrangling @jrea-rmi?

![image](https://user-images.githubusercontent.com/596279/200875933-39b2df7c-1011-45a7-b18a-7cc94c11fd8f.png)

**Comment by zaneselvans** [comment]
Ah okay great to know the `beginning_balance`/`ending_balance` will be useful for data validation!  Will add this check in the transform. Were there any other similar fixes you came across? Where would I look in your code to find them? I'm not seeing it in the `f1_plant_in_service` module immediately.

**Comment by jrea-rmi** [comment]
https://github.com/rmi-electricity/utility-transition-hub/blob/801f457b8dd1294999690776a9f7b45f265cf6c9/hub/f1_plant_in_service.py#L1

I don't think I ever implemented that fix, because for this table I was just interested in the end of year values. And I don't remember or see any other custom data fixes for this table

**Comment by zaneselvans** [comment]
@zschira @cmgosnell Parsing the metadata for the XBRL derived `electric_plant_in_service` table, I've found what seems like a weird inconsistency, and I'm wondering if we're introducing it or if it's FERC being bad about their naming conventions (which would not surprise me one bit).

In most cases the instant and duration tables use exactly the same names for their columns, except that the columns in the duration table have suffixes indicating which quantity they represent (`_additions`, `_retirements` etc.)  **However**, it looks like this isn't **universally** the case 😭.

I am primarily seeing this in the general plant group, though there are a handful of others:
```py
instant_cols = [
    'communication_equipment',
    'office_furniture_and_equipment',
    'structures_and_improvements',
    'tools_shop_and_garage_equipment',
    'miscellaneous_equipment',
    'transportation_equipment',
    'laboratory_equipment',
    'land_and_land_rights',
    'stores_equipment',
    'power_operated_equipment',
    'other_tangible_property',
]
pd.read_sql("electric_plant_in_service_204_instant", ferc1_xbrl_engine)[instant_cols]

# I should only have to add the "_additions" suffix here, not the "_general_plant"!
duration_cols = [col + "_general_plant_additions" for col in instant_cols]
pd.read_sql("electric_plant_in_service_204_duration", ferc1_xbrl_engine)[duration_cols]
```

The other problematic categories are:
```py
bad_cats = [
    'installations_on_customer_premises_distribution_plant',
    'fuel_holders_products_and_accessories_other_production',
    'structures_and_improvements_nuclear_production',
    'leased_property_on_customer_premises_distribution_plant',
    'energy_storage_equipment_production_other_production',
    'asset_retirement_costs_for_regional_transmission_and_market_operations_regional_transmission_and_market_operation_plant'
]

The inconsistent naming between the instant and duration tables also appears in the original FERC Taxonomy, so it doesn't look like it's an issue with our parsing and extraction. They're just being inconsistent.

Rather than having a bunch of special casing everywhere to be able to deal with this, I'm inclined to "fix" these columns early in the transformation process so that they conform to the naming convention that the other 95% of columns use. Which is fine. But man, annoying.

**Comment by zaneselvans** [comment]
Still need to create some new issues based on the "later tasks" but I think this is nominally done.

**Comment by zaneselvans** [comment]
Jajaja, j/k. Tried to run `tox -e nuke` and found 170 duplicate records in the `plant_in_service_ferc1` table so... need to figure out what happened.

**Comment by zaneselvans** [comment]
Hoookay after some additional investigation it turns out the problem (or... a problem anyway) is in the way we fill in the DBF to XBRL mapping spreadsheet, and this is probably creating a bunch of other issues that we didn't catch... so good thing it made some duplicate records (and jfc we always need to make unit tests for everything).

Somehow, we end up mapping the same xbrl category to more than row in the same year. We haven't mapped them this way so it seems like this must be due to the way we're filling in the years between when things changed.

```py
dbf_xbrl_map = pudl.transform.ferc1.get_ferc1_dbf_xbrl_glue("f1_plant_in_srvce")
df = dbf_xbrl_map[dbf_xbrl_map.report_year==2002]
df[df.duplicated(subset=["xbrl_column_stem"], keep=False)].sort_values(["xbrl_column_stem", "row_number"])
# This assertion should succeed, but it does not.
#assert not (dbf_xbrl_map.groupby(["report_year", "xbrl_column_stem"])["row_number"].nunique() > 1).any()
```

Need to create a unit test with a known expected output to debug and also test this process.

**Comment by zaneselvans** [comment]
Here is a standalone reproduction of the bug...

```py
from io import StringIO
import pandas as pd
from pudl.transform.ferc1 import fill_dbf_to_xbrl_map, read_dbf_to_xbrl_map
test_dbf_xbrl_map = pd.read_csv(
    StringIO(
        """
sched_column_name,report_year,row_literal,row_number,row_type,xbrl_column_stem
test_table1,2000,"Header 1",1,header,"N/A"
test_table1,2000,"Account A",2,ferc_account,account_a
test_table1,2000,"Account B",3,ferc_account,account_b
test_table1,2000,"Account C",4,ferc_account,account_c
test_table1,2000,"Total X",5,total,total_x
test_table1,2002,"Header 1",1,header,"N/A"
test_table1,2002,"Account A",2,ferc_account,account_a
test_table1,2002,"Account B",3,ferc_account,account_b
test_table1,2002,"Header Y",4,ferc_account,"N/A"
test_table1,2002,"Account B1",5,ferc_account,account_b1
test_table1,2002,"Account C",6,ferc_account,account_c
test_table1,2002,"Total X",7,total,total_x
"""
    ), comment="#",
).drop(["sched_column_name", "row_literal"], axis="columns")
filled_dbf_xbrl_map = fill_dbf_to_xbrl_map(df=test_dbf_xbrl_map, dbf_years=range(2000,2004))
assert (filled_dbf_xbrl_map.groupby(["report_year", "xbrl_column_stem"])["row_number"].nunique() <= 1).all()
```

**Comment by zaneselvans** [comment]
Ugh, I accidentally used `==` rather than `=` 🙄. One character fix.

Added a unit test for the DBF-XBRL map filling function that would have caught this error.

**Comment by zaneselvans** [comment]
Annnnnnd, there are still 126 duplicate rows showing up in the 2018 data, but in this case they really are duplicates -- it looks like a utility may have two copies of the plant in service table, and one of them has a lot of null values.

**Comment by zaneselvans** [comment]
Okaaaay, after much continuing hijinx on #2067 all the known issues have been resolved in the Plant in Service table!

@zaneselvans don't forget to make issues out of the remaining tasks!

**Comment by jrea-rmi** [comment]
@zaneselvans I'd like to propose a couple of edits to the pudl plant_in_service_ferc1 table:

1. I think it'd be useful to add a column that identifies the category of plant that the row corresponds to (intangible plant, steam production plant, transmission plant, etc) so that I don't have to scan through and identify those rows myself if I want to aggregate.
2. total and subtotal rows should be removed, so that aggregation can be done using the above identifier column(s). For example, the current version of the pudl table includes a subtotal "general_plant_excluding_other_tangible_property_and_asset_retirement_costs_for_general_plant", that equals the sum of a bunch of other general plant lines, and is useless redundant information. The total "general_plant" line would also create double-counting. Or is the idea that those lines are all labeled with row_type=="calculated", and if I want to aggregate, then i should filter those lines out first?

If there's another way to, for example, get the total transmission plant value, then that'd work for me too.

**Comment by zaneselvans** [comment]
We still need to add the structures that make aggregation easy.

Do you know if there are there differences between the aggregations you need to be able to do, and the aggregations that are built into this and other tables via the subtotals and totals that they report? All of the calculated lines are described in the XBRL metadata with machine readable formulae, so if the groupings of rows that we need to be able to aggregate map directly to the groupings of rows that are go into those calculations, we'll be able to use their calculations to define the aggregations across the board for all the tables. This would also mean we don't have to guess at the sign conventions and apply them to every value in order to make all aggregations into simple sums (which would break things if there are multiple calculations that use the same values but with different signs/weights).

The idea of the `ferc_account_label` is that it provides a unique ID for each row with a distinct meaning across all the years of data, which other things can reference. There are a couple of different ways we've talked about using them to implement aggregations. One is to compile an association table that can be merged onto this table with the different categories / levels of aggregations like what you're describing, allowing different groupby-sum operations. That will definitely work for the `plant_in_service` table, but it's not 100% clear to me that it will work in general across all the tables that need aggregating. Are they all sums? Can all of the records have only a single sign convention for all of the aggregations they're involved in? Is there a single convention that will work for turning hierarchical aggregations with different numbers of levels into a tabular form where they all have to have the same number of levels?

It would also be great if there's a programmatic way to generate the aggregations / these association tables from the XBRL metadata so we don't have to manually compile them all. But for the moment we can definitely make one for the plant in service table that reproduces the aggregations you've already got.

**Comment by jrea-rmi** [comment]
The aggreagations I see us doing for the plant in service table are to the technology level, with or without asset retirement costs.

I figure the aggregation by technology is in the XBRL taxonomy, and filtering out the asset retirement costs can be done based on listing the rows to exclude before aggregating.

Everything in the plant in service table is groupby.sum(), but agree that will not work in general for other tables that have minus signs in their calculated fields, without a label or aggregation function. I'm still curious to see a case where a field has a different sign for different aggregations, as far as I've seen each record has a single sign convention.
