### ISSUE TITLE
Make `ferc1_to_sqlite` database generic to all FERC forms

### ISSUE THREAD

**Issue by zschira** [catalyst-cooperative/pudl#1861]
To be able to publish extracted XBRL data from all FERC Forms, the `ferc1_to_sqlite` script needs to be made more generic (`ferc_to_sqlite`), so PUDL can create all of the raw databases.

## Tasks

- [x] Make XBRL datastore generic
- [x] Add settings for all forms that validate years
- [x] Use new settings to create SQLite database

**Comment by zschira** [comment]
Merged into `xbrl_integration`.
