### ISSUE TITLE
Create a github action to update and sync the datastore caches

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1895]
Create a github action that runs the datastore script to update the GCS cache if any new DOIs have been added to the code. The action should also sync the `internal-zenodo-cache` and `zenodo-cache` buckets. 

@zaneselvans should this action checkout `dev` or `main` for the updated DOIs in the datastore script?

https://github.com/catalyst-cooperative/pudl/blob/d294cb52b62b6adf18384b2bbb1be15c84667e6f/src/pudl/workspace/datastore.py#L140-L159

I think `dev` so nightly builds won't have to populate the GCS cache. 

## TODOs
- [x] Create a service account for the action with permission to read and write to the internal and public cache
- [x] Create steps to setup pudl environment
- [x] Step to run the `pudl_datastore` command to update the internal cache
- [x] Step to authenticate gcloud command
- [x] rsync internal cache to public cache

**Comment by zaneselvans** [comment]
I think it has to check out `dev` otherwise it'll never update anything that's needed for the nightly builds, which run on `dev`. Right?

**Comment by bendnorman** [comment]
Groovy, just wanted to double-check.

**Comment by zaneselvans** [comment]
It's a whole separate versioning regime really. At some point I think we should have 2 actions running nightly:
* **First:** one that scrapes the publishing agency websites, and creates new candidate archives to upload, and if there are any new / changed files (based on their hashes) it creates new draft Zenodo depositions and notifies us to review and click "publish"
* **Second:** one that has a list of "concept DOIs" it checks every night for new versions of the data (each concept DOI identifies an archive lineage, e.g. `ferc1` or `eia923`). If there are new versions in any of the archive lineages it tracks, then it uploads them into the internal zenodo cache, and rsyncs that to the public bucket.

Then we'll have:
* Every version of the data ever published archived.
* Fresh copies of that data available for the ETL to use, regardless of what particular DOI it's referring to.

**Comment by bendnorman** [comment]
Love this idea. Once we get more familiar with Dagster Cloud we could also take advantage of [sensors](https://docs.dagster.io/concepts/partitions-schedules-sensors/sensors) to run both of these workflows.
