### ISSUE TITLE
Add sqldiff step to nightly builds

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1957]
Our validation tests don't catch all data changes so it would be nice to diff the deployed sqlite databases with the candidate nightly build dbs. 

## Questions
- Does it make sense to add a `sqldiff` check to our CI too? We could compare the partial database outputs of the CI tests to a canonical version produced by a successful nightly build run. Comparing subsets of the data won't catch all changes but could catch unexpected data errors earlier. 
- Are we willing to automatically deploy the dbs to datasette if the tests pass but the `sqldiff` finds changes? 

## TODOs
- [ ] Install sqldiff in docker images
- [ ] After the ETL and tests run, diff the databases with the deployed databases in `gs://intake.catalyst.coop`.
- [ ] Add diff output to the pudl-etl.log file. 
- [ ] Maybe: notify slack of any data changes

@aesharpe @zaneselvans
