### ISSUE TITLE
Create a SQLite IO Manager

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1972]
Create a dagster IO Manager that creates a sqlite database for each run, creates all table schemas and handles inputs and outputs. 

## TODOs:
- [x] The IO manager is a critical part of dagster infrastructure so it should be [well tested](https://docs.dagster.io/concepts/io-management/io-managers#testing-an-io-manager)!
- [x] Ensure pandas dtypes are consistent as the data moves to and from the database. One known issue is pandas likes to convert nullable integer columns to floats. This will likely require looking up the correct types in metadata data structure or reading the database types. How do we want to handle tables that don't have metadata yet? 
- [x] Decide how to convert asset_key to a table name. `context.asset_key` returns a list of asset key components. Seems like [AssetKey.to_python_identifier() is a decent option](https://github.com/dagster-io/dagster/blob/33b347d20c403b81fd78536f068a4349e2a88d1e/python_modules/dagster/dagster/_core/definitions/events.py#L129).

**Comment by bendnorman** [comment]
## Rerun Issue
My current iteration of the a SQLite manager that create a new sqlite db for each run works well, except it produces an error when rerunning a subset of a DAG made of assets. However, I am able to rerun parts of a DAG made of ops. Here's the error:
```
dagster._core.errors.DagsterInvariantViolationError: Attempting to access run_id, but it was not provided when constructing the OutputContext
  File "/Users/bendnorman/opt/anaconda3/envs/pudl-dev/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 224, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/bendnorman/opt/anaconda3/envs/pudl-dev/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 322, in core_dagster_event_sequence_for_step
    for event_or_input_value in ensure_gen(
  File "/Users/bendnorman/opt/anaconda3/envs/pudl-dev/lib/python3.10/site-packages/dagster/_core/execution/plan/inputs.py", line 501, in load_input_object
    yield from _load_input_with_input_manager(input_manager, load_input_context)
  File "/Users/bendnorman/opt/anaconda3/envs/pudl-dev/lib/python3.10/site-packages/dagster/_core/execution/plan/inputs.py", line 867, in _load_input_with_input_manager
    value = input_manager.load_input(context)
  File "/Users/bendnorman/catalyst/pudl/notebooks/work-in-progress/dagster_prototypes/graph_nesting/asset_iomanager.py", line 64, in load_input
    filepath = self._get_path(context)
  File "/Users/bendnorman/catalyst/pudl/notebooks/work-in-progress/dagster_prototypes/graph_nesting/asset_iomanager.py", line 44, in _get_path
    run_id = context.get_identifier()[0]
  File "/Users/bendnorman/opt/anaconda3/envs/pudl-dev/lib/python3.10/site-packages/dagster/_core/execution/context/input.py", line 391, in get_identifier
    return self.upstream_output.get_identifier()
  File "/Users/bendnorman/opt/anaconda3/envs/pudl-dev/lib/python3.10/site-packages/dagster/_core/execution/context/output.py", line 554, in get_identifier
    run_id = self.run_id
  File "/Users/bendnorman/opt/anaconda3/envs/pudl-dev/lib/python3.10/site-packages/dagster/_core/execution/context/output.py", line 221, in run_id
    raise DagsterInvariantViolationError(
```
and a warning:
```
No previously stored outputs found for source StepOutputHandle(step_key='asset1', output_name='result', mapping_key=None). This is either because you are using an IO Manager that does not depend on run ID, or because all the previous runs have skipped the output in conditional execution.
```
The IO manager does depend on run ID and the DAG doesn't have any conditional execution. After rereading the doc string of the default fs_io_manager, I realized assets might not be built to have persisted copies for each run:

> Assigns each op output to a unique filepath containing run ID, step key, and output name. Assigns each asset to a single filesystem path, at “<base_dir>/<asset_key>”. If the asset key has multiple components, the final component is used as the name of the file, and the preceding components as parent directories under the base_dir.

> Subsequent materializations of an asset will overwrite previous materializations of that asset. So, with a base directory of “/my/base/path”, an asset with key AssetKey([“one”, “two”, “three”]) would be stored in a file called “three” in a directory with path “/my/base/path/one/two/”.

The asset overwriting behavior is consistent with the [snowflake io manager example](https://github.com/dagster-io/dagster/blob/master/examples/project_fully_featured/project_fully_featured/resources/snowflake_io_manager.py). The table data is deleted and replaced by the new data. This is an issue for our ETL because we need to enforce foreign keys. If we rerun an asset that is a parent table in an FK relationship, the old data needs to be deleted, which will produce a FK error. 

## Possible Solutions

**Comment by bendnorman** [comment]
The SQLiteIOManager and tests have been implemented on the  `dagster-asset-etl` branch.

The rerun issue was happening because assets are intended to read and write data to the same location instead of new locations for each run_id. Amending one database file is much simpler and we won't be creating dozens of copies of the output data. [An issue](https://github.com/dagster-io/dagster/issues/9895) has been opened for supporting storing assets in run_id-scoped addresses.
