### ISSUE TITLE
Map FERC 1 DBF rows to XBRL columns for targeted tables

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2040]
We have a draft process for aligning multiple years of DBF data and the corresponding XBRL tables allowing all years of FERC 1 data to be concatenated, now we should actually try and get the priority tables mapped.

## Prep Work
* [x] Check in draft `electric_energy_account` mapping
* [x] Create a CSV associating all DBF and XBRL FERC 1 table names
* [x] Document meaning of all the columns in the `dbf_to_xbrl.csv` template
* [x] Rename `xbrl_column_stem` to `xbrl_factoid` since many things can end up here, loosely related to XBRL Facts, but not exactly. Can refer to rows, or columns, or a portion of a set of related column names, etc.
* [x] Generalize the `row_type` values that are manually assigned in `dbf_to_xbrl.csv` -- not all of the reported values are FERC Accounts. Not all of the calculated values are Totals.
* [x] For simple row-mapped tables, provide mapping instructions & the values to be mapped in the table-specific issue.
* [x] Explore all targeted tables and take notes on how to map / transform them (see list below)
* [ ] #2108 (punted for now b/c it will require a bit of refactoring)

## DBF Tables to Map (dbf:xbrl)

All tables targeted in #1574 that we think need `row_number` DBF/XBRL alignment. Taking notes on the row mapping / likely transformations in the table-specific issues. Tables that are checked off on this list have been explored, but haven't actually been mapped or transformed (unless their issue is closed...).

### key
* 🟢 = table is done
* 📨 = table is in progress
* ⭐ = DBF-XBRL mapping is simple & worth delegating, table is ready to be taken on
* 🟧 = table is ready to be taken on.

### All rehsaping tables
* [x] #1807 (one-to-one) 🟢
* [x] #1819 (one-to-one) 🟢
* [x] #1806 (one-to-one) 📨
* [x] #1810 (one-to-one) ⭐ 
* [x] #1805 (one-to-one) ⭐ 
* [x] #1817 (one-to-one) ⭐ 
* [x] #1816 (one-to-one) 🟧
* [x] #1824 (one-to-one) 🟧
* [x] #1815 (one-to-many, 2 XBRL tables)
* [x] #1808 (one-to-many, 4 XBRL tables)
* [x] #1821  (one-to-many, 8 XBRL tables)
* [x] #1811 (one-to-many, 8 XBRL tables)
* [x] #1823 (one-to-many, 9 XBRL tables)
* [x] #1813 (many-to-one, 2 DBF tables)

## `dbf_to_xbrl_tables.csv`

* This file defines an association table connecting DBF and XBRL derived tables.
* It will replace the `pudl.extract.ferc1.TABLE_NAME_MAP` dictionary.
* A table is necessary because not all mappings are 1-to-1. To produce a given PUDL DB table, we'll frequently need more than one XBRL table as an input, and occasionally need more than one DBF table as an input.

## `dbf_to_xbrl.csv` compilation Instructions

* The purpose of this table is to allow us to map DBF database records to a semantic meaning that is consistent across years, even though the row numbers associated with them changed over time, and further to map that meaning to the corresponding XBRL entities, if they exist.
* Within tables that have been mapped, **every single (`row_number`, `report_year`) tuple should be mapped to an identifier**. For DBF row numbers that correspond to an XBRL value in the modern data, that XBRL value should be used. 
* The exact form of the XBRL value will vary depending on the reported structures of the original DBF & XBRL data, and the output structure which we are targeting.
* This table has a primary key of: (`sched_table_name`, `row_number`, `report_year`). Each record indicates what `row_literal` string was associated with a given row number, in that table, for that year.
* Not every originally reported (`sched_table_name`, `row_number`, `report_year`, `row_literal`) tuple from the `f1_row_lit_tbl` has been included in this table, since in most years, the meaning of a row does not change compared to the previous year. Only the initial values, and any newly changed values are reported, since the intervening duplicated meanings can be reconstructed from that information, and it means we have to map far fewer values.
* There are some instances in which new XBRL values have no corresponding DBF rows (e.g. some utility-scale energy storage facilities that only appear in 2021 and later). These XBRL values will not appear in this file at all, and that's fine.
* There are other instances in which a quantity was reported in the DBF data, but never appears in the XBRL data because it stopped being reported prior to 2021. **These values do need to be mapped to something** it just can't be an ID that's pulled from XBRL. We need to come up with a naming convention for such values so they are recognizable. These values will be used only to align historical DBF data and will be NA in later years. We know this kind of discontinuation happens at the whole-table level (e.g. there are many tables that only contain data from 1994-2002) but does it also happen to an individual row number within a table? May need to change the way this mapping is filled in to accommodate single-row discontinuation.

### Column documentation

* **`sched_table_name`** (PK): The DBF database table name found in the original FERC Form 1 DBs. These values come from the `f1_row_lit_tbl`.
* **`row_number`** (PK): The row number appearing in `sched_table_name` in association with records described by the `row_literal` value. These values come from the `f1_row_lit_tbl`.
* **`report_year`** (PK): The year that the data pertains to.  These values come from the `f1_row_lit_tbl`.
* **`row_literal`** (original data): A freeform human readable string used to annotate a given row on the FERC Form 1.  These values come from the `f1_row_lit_tbl`.
* **`row_type`** (manually assigned): indicates what kind of value is being reported in the DBF table in association with that row number.
    * `header`: A label row that appears in the DBF only for display purposes. Often grayed out in the Form 1 PDF. Will not have any corresponding value in the XBRL data.
    * `reported_value`: A directly reported value in the DBF data, meaning it is not calculated from other values **in that table** (it may in fact correspond to some calculation derived from values reported in other tables).
    * `calculated_value`: A value which is derived from other values **in that table** -- typically a sum (Total rows) or a net value (credit - debit) of some kind. Often there's an annotation in the `row_literal` field that indicates (to humans) what other rows are used to calculate the value. These values will typically also appear in XBRL, with a formula for their calculation reported in the XBRL metadata.
* **`xbrl_factoid`** (manually assigned): A label associated with the XBRL entity that we are associating with the DBF `row_number`.  This isn't actually an "XBRL Fact", and given the many kinds of structures that the DBF row numbers map to, these aren't always referring to the same kind of thing -- sometimes it's a column name from the XBRL DB, sometimes it's a portion of a column name shared by several different columns that report different aspects of the same column. Sometimes it's a categorical value found in the XBRL rows. that should be associated with the value indicated by the DBF `row_literal` value, given the context of the table.  These values are derived from the XBRL taxonomy and/or data, and the association between them and the `row_literal` value must be assigned manually, with the exact pattern and meaning defined on a table-by-table basis as the transforms require.
* **`notes`** (manually assigned): Human readable notes, indicating anything unusual about this particular association. E.g. a mismatch between the old row literal value and the new XBRL name, and the reasoning behind why they were associated anyway, or the fact that the XBRL entity did not conform to an otherwise standard naming convention and has to be renamed, or instances where a single row in earlier years is replaced by multiple more granular rows in later years.

**Comment by zaneselvans** [comment]
I used the `xbrl_tables` and `dbf_tables` produced below as the building blocks of the new `dbf_to_xbrl_tables.csv` file, which contains an association table (sadly many-to-many) linking together old DBF and new XBRL database tables. This will be one of the inputs into the column-level mapping.

* Often there's a one-to-one correspondence between DBF & XBRL tables.
* Less often but still commonly, a single DBF table becomes many XBRL tables, especially in the depreciation and amortization tables.
* Very occasionally multiple DBF tables are consolidated into a single XBRL table, and it often seems to be in cases where there was an artificial separation between a couple of DBF tables that really should have been a single table.

```py
import importlib
import pudl

pudl_settings = pudl.workspace.setup.get_defaults()

ferc1_engine = sa.create_engine(pudl_settings["ferc1_db"])
ferc1_xbrl_engine = sa.create_engine(pudl_settings["ferc1_xbrl_db"])

xbrl_tables = (
    pd.Series(sa.inspect(ferc1_xbrl_engine).get_table_names(), name="xbrl_table")
    .to_frame()
    .replace(r"(_duration|_instant)$", "", regex=True)
    .drop_duplicates()
    .reset_index(drop=True)
)

dbf_tables = (
    pd.Series(sa.inspect(ferc1_engine).get_table_names(), name="dbf_table")
    .to_frame()
    .drop_duplicates()
    .reset_index(drop=True)
)

def dbf_table_report_years(dbf_table: str, engine: sa.engine.Engine) -> dict[str, int]:
    dbf_df = pd.read_sql(dbf_table, ferc1_engine)
    try:
        start_year = min(dbf_df["report_year"])
        end_year = max(dbf_df["report_year"])
    except:
        start_year = pd.NA
        end_year = pd.NA
    output = {"dbf_table": dbf_table, "dbf_start_year": start_year, "dbf_end_year": end_year}
    logger.info(f"  {output}")
                
    return output

minmax_years = [dbf_table_report_years(dbf_table, ferc1_engine) for dbf_table in dbf_tables.dbf_table]

with importlib.resources.open_text("pudl.package_data.ferc1", "dbf_to_xbrl_tables.csv") as file:
    dbf_to_xbrl_tables = pd.read_csv(file)

combined = pd.merge(
    dbf_to_xbrl_tables,
    pd.DataFrame(minmax_years),
    how="left",
)
```

* There are many DBF tables that don't have any corresponding table in XBRL. In many cases this is because those tables haven't been reported in a long time (many of them were phased out or re-organized after 2002).
* There's one new XBRL table in 2021 related to energy storage: `energy_storage_operations_large_plants_414` which does not appear in any DBF data.
* And then there's a handful of DBF tables that were being reported right up through 2020, but that don't have any clear analog in the XBRL. We should dig into these in more detail and see if they were consolidated with other tables, or if they really stopped being reported:

```py
dbf_without_xbrl = combined[
    (combined.xbrl_table.isna())
    & (combined.dbf_end_year == 2020)
]
dbf_without_xbrl
```
|     | dbf_table          |   xbrl_table |   dbf_start_year |   dbf_end_year |
|----:|:-------------------|-------------:|-----------------:|---------------:|
|   3 | f1_208_elc_dep     |          nan |             2004 |           2020 |
|   6 | f1_324_elc_expns   |          nan |             2004 |           2020 |
|   7 | f1_325_elc_cust    |          nan |             2004 |           2020 |
|   9 | f1_338_dep_depl    |          nan |             2004 |           2020 |
|  13 | f1_399_mth_peak    |          nan |             2004 |           2020 |
|  44 | f1_allowances      |          nan |             1994 |           2020 |
|  45 | f1_allowances_nox  |          nan |             2009 |           2020 |
|  78 | f1_elctrc_oper_rev |          nan |             1994 |           2020 |
| 110 | f1_othr_pd_in_cptl |          nan |             1994 |           2020 |
| 111 | f1_othr_reg_assets |          nan |             1994 |           2020 |
| 139 | f1_rg_trn_srv_rev  |          nan |             2006 |           2020 |
| 140 | f1_row_lit_tbl     |          nan |             1994 |           2020 |
