### ISSUE TITLE
Enable hierarchical aggregation of electric plant in service table

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2076]
There are a bunch of categories and subcategories of FERC accounts reported in the `plant_in_service_ferc1` table, which need to be programmatically aggregated. This problem isn't unique to this table, but we don't know enough about how it will work across the board to design something general. So first we're going to do it "by hand" a few times to learn more.

## Tasks
* [ ] Manually compile an association table of categories to aggregate with `ferc_account_label` as its primary key. These aggregations should also allow reproduction of the reported aggregate categorical totals.
* [ ] Verify that aggregations based on our categories match reported totals in 2021 XBRL data.
* [ ] Evaluate match between our aggregations & reported totals for DBF data (1994-2020)
* [ ] #2066 (otherwise those extreme outliers will throw aggregations way out of whack)

## See Also:
* #2012
* #2074 
* `calculations` column in the normalized XBRL taxonomy for this table.
* [RMI FERC Account Names](https://github.com/catalyst-cooperative/rmi-ferc1-eia/blob/main/inputs/ferc_acct_names.csv)
* [FERC Account definitions](https://www.law.cornell.edu/cfr/text/18/part-101) from Cornell Law.
