### ISSUE TITLE
Port existing ETL logic to Dagster

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#2246]

**Comment by bendnorman** [comment]
I think this is the remaining work to get dagster-asset-etl merged into dev:

- [ ] #2296. This will allow us to produce the ETL outputs on dev and dagster-asset-etl in the same environment so we can diff the data. #2294 Seems like @jdangerx is on this.
- [ ] #2301 @zschira we could work on this together.
- [ ] I am working on #1872
- [ ] I need to create an issue for comparing sqlalchemy schemas so people don't get unexplained database errors when the metadata changes.
- [ ] #2295

**Comment by zaneselvans** [comment]
I think this is basically done and could be closed. Maybe we should post an announcement in GitHub Discussions and do some Tweetes.
