### ISSUE TITLE
Convert EIA-861 + FERC-714 service territory and state electricity demand to Dagster assets

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#2437]
Notes on how to do this:
- Interim table transforms in `pudl.output.ferc714` should use the standard io manager
- `compile_geoms()` should have a factory function, iterating over entity type. The save to geoparquet function has been flaky, if we are able to get it working we could use geoparquet and write a geoparquet io manager. Otherwise, we can strip geometry and  save as a table. Extensive additional work on the geometrical component is a low priority in this iteration of the transition.
- Whatever is implemented in `state_demand.py` should be used as a default for the `ba_ids` and `util_ids`, but these should be parameters passed in by dagster's `context` to enable manual changes.
- Best order to implement change in: service_territory -> FERC 714 -> state_demand
- Rip out the `Respondents` class in `pudl.output.ferc714`
- In `pudl.output.ferc714`, the `summarize_demand` and `fipsify` tables are the best candidates for inclusion into PUDL. The other two tables are just upstream intermediate outputs.

```[tasklist]
- [x] `pudl.output.ferc714.Respondents.annualize`
- [x] `pudl.output.ferc714.Respondents.categorize`
- [x] `pudl.output.ferc714.Respondents.summarize_demand`
- [x] `pudl.output.ferc714.Respondents.fipsify`
- [x] `pudl.output.ferc714.Respondents.georef_counties`
- [x] `pudl.output.ferc714.Respondents.georef_respondents`
- [x] `pudl.analysis.service_territory.compile_geoms(entity_type="util")`
- [x] `pudl.analysis.service_territory.compile_geoms(entity_type="ba")`
- [x] `pudl.analysis.state_demand.predict_state_hourly_demand`
```

**Comment by e-belfer** [comment]
Merged in #2550
