### ISSUE TITLE
Rename AWS bucket

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#2574]
Rename the AWS s3 bucket from `intake.catalyst.coop` to `pudl.catalyst.coop` so it has a took independent name. Also, we're supposed to have a 1-month retention policy on s3 bucket logs, so we need to setup a bucket in GCP that can store our s3 logs long term.

```[tasklist]
- [x] Delete the junk tagged outputs in GCS and S3
- [x] Add `v2022.11.30.post1` to AWS
- [x] Create a new s3 bucket called `pudl.catalyst.coop`.
- [x] Create a [log bucket called](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html#enable-server-logging) `pudl.catalyst.coop-logs` for `pudl.catalyst.coop` bucket. AWS Open Data Program requires we set a 1 month retention policy.
- [x] Create a GCS bucket called `pudl.catalyst.coop-logs` to retain all logs from `pudl.catalyst.coop-logs` bucket in s3.
- [x] Create AWS credentials for the VM to dump outputs to s3 bucket. Test existing credentials
- [x] Create a GCS service account, give it access to gs://pudl.catalyst.coop-logs. Add keys to repo.
- [x] Create AWS credentials for a user that has access to s3://pudl.catalyst.coop-logs. Use [WIF](https://github.com/aws-actions/configure-aws-credentials)?
- [x] Create a reoccurring job that syncs the s3 logs with GCS logs. Test it's working as expected!
- [x] Update the bucket name in docs and nightly build scripts.
- [x] Update the URLs to use the new name.
- [x] Update the aws registry repo https://github.com/awslabs/open-data-registry/pull/1998
- [x] Stop nightly builds from dumping workflow-triggered outputs into AWS bucket. Will have to pass an env var for the trigger method. Add to distribution bucket if branch is `dev` or action was triggered by a `tag`. This will exclude `workflow_dispatch` triggers.
- [x] Sync all of the buckets
- [x] Set up retention policy on gs://pudl.catalyst.coop
```
```[tasklist]
### Tasks
- [x] enable retention policy on s3://pudl.catalyst.coop
- [x] Does the new tag / dev check work in the vm
- [x] Does the vm have access to the s3 bucket with the existing credentials?
- [x] Check vm has access to gs://pudl.catalyst.coop
- [x] create keys for pudl-s3-logs-sync
```

**Comment by bendnorman** [comment]
Do folks have opinions on what we should rename the bucket to? Some ideas:
- `pudl.catalyst.coop`
- `pudl-outputs.catalyst.coop`
- `outputs.catalyst.coop`

I like `pudl.catalyst.coop` because the S3 is a primary mode of access for all PUDL data.

**Comment by zaneselvans** [comment]
The `2022.11.30.post1` release didn't end up going out really -- it only changed a dependency in the Python packaging, and that change couldn't be propagated to the conda packaging, and no data changes were associated with it.  So I don't think it actually needs to be updated on AWS.

**Comment by bendnorman** [comment]
Sounds good. Waiting to hear back from AWS folks on the best way to rename the bucket.

**Comment by bendnorman** [comment]
Are we concerned about breaking software that depends on the old bucket name? We could have two buckets for a bit and let the world know we'll be deprecating the old name.

**Comment by zaneselvans** [comment]
Ugh, I hate backward compatibility.  Do we have any information about what is hitting the existing bucket address(es)?

**Comment by bendnorman** [comment]
We have logs for the AWS access but I haven't added them to our metrics ETL. 

It looks like we might be able to redirect requests from [the old bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-page-redirect.html).

**Comment by rousik** [comment]
From my cursory search, links do not seem to be supported.

**Comment by bendnorman** [comment]
It might make sense to make an alias that redirects a bucket download URL so we don't have to keep changing the URL if the bucket name/location of the data changes. For example, `data.catalyst.coop/pudl.db` could redirect to whatever cloud bucket we use. This would be helpful if we do another bucket name change or AWS stops covering our storage fees.

**Comment by jdangerx** [comment]
Now that #2793 is merged, is this done?

**Comment by bendnorman** [comment]
Waiting on merging this PR in the [AWS repo](https://github.com/awslabs/open-data-registry/pull/1998).
