### ISSUE TITLE
Create documentation that explains new naming convention to users and contributors

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#2868]
- user-facing documentation explains new naming convention
- contributor-facing documentation explains asset creation guidelines & goes in depth about intermediate assets
```[tasklist]
### Tasks
- [x] Add section to release notes explaining the name change
- [x] Create a final old table_name, new_table_name and pudltabl method reference for uses
- [x] Add a note about ferc schedule descriptions in the naming convention docs
- [x] Add a note that assets with multiple sources like in assn, should use the same order
- [x] Explain when it is appropriate to use `pudl` as a source. See comment https://github.com/catalyst-cooperative/pudl/issues/2992#issuecomment-1791493924
```

**Comment by bendnorman** [comment]
Closed https://github.com/catalyst-cooperative/pudl/pull/2874 and https://github.com/catalyst-cooperative/pudl/pull/3028
