### ISSUE TITLE
Make quicker quarterly updates to PUDL EPA CEMS, EIA 923 and EIA 860 data

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl#2902]
### Description
With the support of RMI, the goal of the project is to make it possible to integrate quarterly updates for CEMS, EIA 923M and EIA 860M data within 1-2 weeks of new data release. To do this, we are going to 1) automate archiving of new data, with the support of additional data validation checks on our archiver, 2) redesign PUDL to handle quarterly and monthly data formats and 3) integrate YTD data to test it all.

#### Archiver infrastructure updates
Goal: Generate robust report of archiver results to enable quick (<.25 hour per dataset) manual review and approval of draft production archives run by Github action.

Current state: Currently, archive runs check for 1) missing files, 2) valid file types, 3) emptiness of zips (in progress) and produce a summary of all changed files. The new default behavior of the ‘auto-publish’ flag allows for the production of a draft production archive in Zenodo for manual approval, removing the need for sandbox runs of an archiver that is known to work. @zschira has seriously improved the archiver’s robustness to large file uploads but this is always a trouble spot and we should anticipate some time required to handle things that come up.

- [ ] Identify and implement 1-2 additional generic validations for all datasets to help us catch remaining gaps (e.g. size of all files hasn’t changed by more than 10%).
- [ ] Identify and implement any dataset-specific validation criteria required (e.g. all quarters present for CEMS).
- [ ] Write a schedule for the archiver action that reflects dataset releases.
- [ ] Write auto-notification of Github action run summary (create issue that says go approve draft, archive failed, no change detected). 
- [ ] Point Github action at production archives.
- [ ] Auto-cache Zenodo archives in Google Cloud Storage.
- [ ] Deal with any robustness issues that arise in the process of archiver updates.

Non-coding tasks required (likely RMI tasks):
- [ ] Identify expected frequency of dataset releases in order to schedule automated archiving
- [ ] Identify any known dataset quirks relevant to the archiving process (e.g., 2015 Q1 CEMS data is mislabelled).

#### Handle monthly data in PUDL

Goal: Design a mechanism to handle monthly data in a system that is designed for annual data. Make structural changes required for each dataset to make this possible, designating new data as YTD data and excluding it from annually aggregated tables.

Current state: 
EIA 860M data is ‘annual’ in nature and already appended on to EIA 860 data. No changes required here.
EIA 923M data has the same format as EIA 923 data, with slightly fewer ‘pages’ (Schedules 2-5 only, which means no emission control table). The column names and layout are the same, with YTD data and blank rows for the months not yet covered.
CEMS is currently downloaded by year-state and will need to be downloaded by quarter instead (one file per quarter, ~2-3Gb per file).

Tasks involved:
- [ ] Write general method to remove YTD data from any annually aggregated outputs.
- [ ] CEMS: Rewrite and test archiver to pull quarterly files rather than state-year
- [ ] CEMS: Repartition extraction process and parquet files.
- [ ] EIA923M: Monthly dataset provided through the same link every month. Add a method to distinguish the monthly file from the annual ones and parse date from website (file name has date of upload, not date of data).
- [ ] EIA923M: Handle the metadata for this YTD file, possibly changing 923M partitions as needed.
- [ ] EIA923M: Add to the extraction process, specifying that only Schedules 2-5 should be extracted (all tables except emission control). 
- [ ] EIA923M: Add a YTD tag to these records and integrate into the annual harvesting process. Drop empty records for months not yet included in the data

#### Doc updates

Goal: make it easier for external contributors to make progress on the annual updates
Current status: Annual doc updates are relatively up to date but require additional elaboration for a few steps.

Tasks involved:
- [ ] Update documentation about how to integrate new data updates

#### Integrate YTD data

Goal: test new infrastructure on YTD data (anticipated Q3 2023).

- [ ] CEMS: Quarterly work of running new data through ETL and debugging any errors. Add any missing plant timezones. Data validation.
- [ ] EIA 860: Quarterly work of mapping files, tabs and columns. Running new data through ETL and debugging any errors. Add any new plants and utilities into plant ID generator. Data validation.
- [ ] EIA 923: Quarterly work of mapping files, tabs and columns. Running new data through ETL and debugging any errors. Data validation.

#### If time, but not essential to project success

- Explicitly specify expected missing partitions for ingested datasets (e.g. no HI data in 2013).
- Write a suite of tests to characterize changes in ingested data at the end of the ETL (data coverage, number of entities, other metrics of completion) and output as report. Will speed up our process of knowing how ‘complete’ monthly data is and how revisions affect data.

#### Future projects that could complement this work
- Remaining tasks in #1418 
- Automating an attempted PUDL ETL on new data (when new data archive released, produce a PR automatically attempting to run it through the ETL to streamline integration fixes).

**Comment by e-belfer** [comment]
With the merging of #3185 and #3186, this issue is complete. Further ongoing quarterly updates will be tracked in individual issues.
