### ISSUE TITLE
Resolve `Event database is locked` error in nightly builds

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#2977]
The dagster SQLite event log database has been locking up more frequently on our nightly build VM. I described the issue and asked for a potential solution in the [dagster repo](https://github.com/dagster-io/dagster/discussions/17370#discussion-5773026). We've encountered this issue before #2713, and I think limiting concurrency reduced the frequency of the databases locking up. It's still not totally clear why this issue doesn't happen on our powerful local machines and why this issue comes and goes on our nightly build VMs.

## Potential solutions
- Do nothing and live with the nightly builds failing 30 - 50% of the time
- Limit concurrency more and hope the log database locks up less. This is probably our best short-term solution.
- [Dagster recommends](https://github.com/dagster-io/dagster/issues/2884#issuecomment-687967814) using Postgres to allow concurrent writes. We'd have to configure our nightly builds to use a [Cloud SQL Postgres instance](https://docs.dagster.io/deployment/guides/gcp).
   - How expensive will the Cloud SQL instance be? How does the price compare to Dagster Cloud?
   - Is it problematic to have our local event log database be different than our nightly build database?
   - Does the SQL instance need to be up all the time or can we launch it from within the nightly build VM?
   - I don't think we need to store all dagster event logs from all nightly build runs in a database. Can we spin up a new database for each nightly build run or can we clear the database after each run?
- Migrate to using dagster cloud. I need to look into what this would actually look like: how expensive is it, how would it interact with our github action tox tests, how would we run our test suite? How much is it?
- Use duckdb as the event storage backend.

What should our local, CI and nightly build environments look like at a high level?
```[tasklist]
### Tasks
- [x] Allow max concurrency for pudl_etl command. Will this improve performance?
- [x] Setup Cloud SQL Postgres
- [x] Create Cloud SQL Postgres quote
- [x] Figure out how to spin database up with full builds. Could spin it up via the github action but will have to spin it down from within the VM container. I think Google Batch has more support for proper setup and shutdown procedures. Would probably be best to have it always running given we might have multiple nightly builds running with Google Batch. Could we use Terraform to programatically create and delete databases?
- [x] How to set DAGSTER_HOME in container and add postgres connection details to $DAGSTER_HOME/dagster.yaml
- [x] Decrease database disk size
```
