### ISSUE TITLE
Iron out association asset names

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3030]
@zaneselvans [suggested we alphabetize multiple source](https://github.com/catalyst-cooperative/pudl/issues/2992#issuecomment-1791482501) names when they appear in an asset name. I went through all of our association tables and realized we not super consistent with how we name these types of assets:

- Association assets that link multiple sources and need to be alphabetized
  - core_epa__assn_epacamd_eia
  - core_epa__assn_epacamd_eia_subplant_ids
  - core_pudl__assn_raw_epacamd_eia
  - _core_epa__assn_epacamd_eia_unique
- Mostly our association assets follow this naming convention `{layer}_{source of association asset}__assn_{datasets being linked}_{entity being linked}`. However, we aren't consistent about the order of {datasets being linked} and {entity being linked}. For example:
  - core_pudl__assn_plants_eia
  - core_pudl__assn_plants_ferc1
  - core_pudl__assn_utilities_eia
  - core_pudl__assn_utilities_ferc1
  - core_pudl__assn_utilities_ferc1_dbf
  - core_pudl__assn_utilities_ferc1_xbrl
- I found one association asset that still has `assn` at the end of the asset name.
  - core_eia860__yearly_boiler_emissions_control_equipment_assn

I propose we rename these assets to follow this convention: `{layer}_{source of association asset}__assn_{datasets being linked}_{entity being linked}`

```[tasklist]
### Tasks
- [x] core_epa__assn_epacamd_eia -> core_epa__assn_eia_epacamd
- [x] core_epa__assn_epacamd_eia_subplant_ids -> core_epa__assn_eia_epacamd_subplant_ids
- [x] raw_epacamd_eia -> raw_pudl__assn_eia_epacamd (i actually don't were the raw should be here)
- [x] _core_epa__assn_epacamd_eia_unique -> _core_epa__assn_eia_epacamd_unique
- [x] core_pudl__assn_plants_eia -> core_pudl__assn_eia_pudl_plants (assuming pudl is also a dataset here & below)
- [x] core_pudl__assn_plants_ferc1 -> core_pudl__assn_ferc1_pudl_plants
- [x] core_pudl__assn_utilities_eia -> core_pudl__assn_eia_pudl_utilities
- [x] core_pudl__assn_utilities_ferc1 -> core_pudl__assn_ferc1_pudl_utilities
- [x] core_pudl__assn_utilities_ferc1_dbf -> core_pudl__assn_ferc1_dbf_pudl_utilities (assuming ferc1_dbf is considered a dataset)
- [x] core_pudl__assn_utilities_ferc1_xbrl -> core_pudl__assn_ferc1_xbrl_pudl_utilities
- [x] core_eia860__yearly_boiler_emissions_control_equipment_assn -> core_eia860__assn_yearly_boiler_emissions_control_equipment
- [x] Explain how to name `assn` tables in the docs
- [x] Create migrations, Run local ETL
```

**Comment by cmgosnell** [comment]
> I propose we rename these assets to follow this convention: {layer}_{source of association asset}__assn_{datasets being linked}_{entity being linked}

I think this is the way!! which does - somewhat annoyingly- mean that we will have some instances where the source dataset is also included in the datasets being linked. but i think that is okay and will make everything more consistent!!

**Comment by cmgosnell** [comment]
Which i thiiiink would mean this:
- `core_epa__assn_eia_epacamd`
- `core_epa__assn_eia_epacamd_subplant_ids`
- `core_pudl__assn_raw_eia_epacamd` (i actually don't were the raw should be here)
- `_core_epa__assn_epacamd_eia_unique`
- `core_pudl__assn_eia_pudl_plants` (assuming `pudl` is also a dataset here & below)
- `core_pudl__assn_ferc1_eia_plants`
- `core_pudl__assn_eia_pudl_utilities`
- `core_pudl__assn_ferc1_pudl_utilities`
- `core_pudl__assn_ferc1_dbf_pudl_utilities` (assuming `ferc1_dbf` is considered a dataset)
- `core_pudl__assn_ferc1_xbrl_pudl_utilities`

If the assn is within one dataset should it still get the `{datasets being linked}`:
- core_eia860__assn_yearly_eia860_boiler_emissions_control_equipment
- OR just `core_eia860__assn_yearly_eia860_boiler_emissions_control_equipment`

**Comment by bendnorman** [comment]
These look good to me! I think if the assn is within one datsete we shouldn't include `{datasets being linked}` just so there isn't too much duplication. So boiler emissions would be `core_eia860__assn_yearly_boiler_emissions_control_equipment`

**Comment by bendnorman** [comment]
Closed by https://github.com/catalyst-cooperative/pudl/pull/3035
