### ISSUE TITLE
Make a transformer to add a column w/ a standard value

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#3072]
```[tasklist]
### Tasks
- [x] build standard transformer in `pudl.transform.classes` that adds colums(s) with standard value(s)
- [x] add this transform step into `pudl.transform.ferc1.Ferc1AbstractTableTransformer.transform_main`
- [x] add a metadata transform step as well
- [x] add a calculations table transform step as well
- [x] ensure this works for the `add_corrections` and corrections in table metadata & calculations
- [x] convert all of the current assign-ing of (mostly) single value columns into a transform params
```

this will be a bit of a weird transformer because one parameter will need to effect outcomes in many places across the transform. There will be a normal looking transform `TransformParams` & transform function & method that actually does the assignment of a new column. But this transform param will also need to be access in the methods/functions that muck with the table metadata and calculations.

**Comment by cmgosnell** [comment]
Okay in service of #3404 i learned that the calculation components are not always getting the dimension tags when we have applied them uniformly across all tables.

A lil example:

```python
from pudl.output.ferc1 import NodeId
from pudl.etl import defs
_core_ferc1_xbrl__calculation_components = defs.load_asset_value("_core_ferc1_xbrl__calculation_components")
calc_idx = [c for c in list(NodeId._fields) if c != "table_name"] # remove tbl name bc long
parent_idx = [f"{c}_parent" for c in calc_idx]
_core_ferc1_xbrl__calculation_components[_core_ferc1_xbrl__calculation_components.xbrl_factoid_parent == "nuclear_fuel_net"][
      parent_idx + calc_idx
]
```

![Image](https://github.com/catalyst-cooperative/pudl/assets/25487998/41884ab6-da3c-4322-a04e-3800a8270872)

I believe this dimensions are being dropped and/or not being assigned in `add_calculation_corrections`. But in general I've had a hard time seeing where we've added these uniform dimensions across the board and i think fixing this `_correction` problem will be much easier to do with a parameterized transform for this adding of uniform dimension columns.

**Comment by cmgosnell** [comment]
this was closed via #3409
