### ISSUE TITLE
Use Splink as a tool for understanding entity-matching models

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3149]
Splink provides a lot more under-the-hood visibility than our existing FERC-EIA model does, while following a similar methodology and providing similar results.

If FERC-EIA model suddenly gets worse, we can use the Splink model and visualizations to understand why.

If you want to start improving the FERC-EIA model, a Splink model that closely mirrors the FERC-EIA model would be a good place to start trying to improve things.

Clearly it would be nice if the "production" model and the "diagnostic" model were the same model, but this doesn't have to be true for Splink tooling to be useful.

```[tasklist]
## Success criteria
- [ ] notebook in /devtools that helps people understand the existing FERC-EIA match model through Splink
- [ ] (nice to have): FERC-EIA match in PUDL uses Splink
```

```[tasklist]
## TODO
- [ ] port CCAI splink notebook to PUDL
```
