### ISSUE TITLE
Make a utility rate base table using exploded assets

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#3203]
```[tasklist]
### Tasks
- [x] pull in both balance sheet explosions & filter by in_rate_base
- [x] ensure all corrections have tags
- [x] add the one additional element from a non-exploded table: working capital xbrl_factoid * (1/8?)
```

```[tasklist]
### Tasks
- [x] make unit tests build a forest
- [x] write unit tests for tag propagating (3 passes - leaf-ward, root-ward, correction-ward) in annotated_forest
- [x] add 3 ways of propagation - leaf-ward, root-ward, correction-ward in annotated_forest
- [x] determine whether we want to expect to have all nodes tagged even if they have no tags (i.e. do they show up in `annotated_tags = nx.get_node_attributes(annotated_forest, "tags")`) -> No. It doesn't seem like we need this at all and it required an additional input into the forest builder so I removed it.
- [x] Remove the metadata df as an input into the forest builder. it wasn't strictly necessary.
- [x] are we enforcing tree structure now? (are we removing stepparents/stepchildren?) YES
- [x] bunch of nothing in assets and liabilities from 2005-2020 #3300
- [x] pull in the three propagations into individual _functions/_methods
- [x] add validation test: does rate base table have more than one _correction factoid?
- [x] add validation test: do exploded tables have more tags?
```
