### ISSUE TITLE
Remove _out tables from datasette and sort tables

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3223]
Right now tables are ordered alphabetically on data.catalyst.coop (`_out`, `core`, `out`). This isn't ideal because it promotes the table in the reverse of the ideal order. We should reorder the tables so `out` is at the top of the page, then `core`, then `_out`.

We could also just remove `_out` tables but then there will be a discrepancy between the data on data.catalyst.coop and the data in the sqlite databases. The `_out` tables will be removed from the database once the #3215 is completed.

```[tasklist]
### Tasks
- [ ] Hide `_out` tables on datasette
- [ ] Resole bug that resulted in most output tables not having any metadata on datasette
- [ ] Sort tables so `out` tables are first
```
