### ISSUE TITLE
Release v2024.02.05 checklist

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3316]
We'll do this once #3052 is closed.

Full documentation of process [here](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/run_a_release.html).

```[tasklist]
## Release Checklist
- [x] set a release date & notify team
- [ ] #3342
- [ ] #3344
- [ ] https://github.com/catalyst-cooperative/pudl/pull/3346
- [x] Push v2024.02.05 tag
- [x] Verify that the GitHub (software) release has been published **(multiple failures, see below)**
- [x] Verify RTD build for new version is up to date **(required manual activation of new version)**
- [x] Verify [`catalystcoop.pudl` PyPI (software) release](https://pypi.org/project/catalystcoop.pudl/)
- [x] Verify that [PUDL repo archive on Zenodo](https://zenodo.org/doi/10.5281/zenodo.3404014) has been updated w/ new version
- [x] Wait 6-10 hours for a successful build to complete **(multiple failures, see below)**
- [x] Verify `stable` and version tag point at same git ref **(do manually, see #3347)**
- [x] Verify that RTD docs build for `stable` branch gets updated
- [x] Verify `gs://pudl.catalyst.coop/vYYYY.MM.DD` has the right data.
- [x] Verify `gs://pudl.catalyst.coop/stable` has the right data. **Note: logfile is bigger than in `v2024.02.05`**
- [x] Verify `s3://pudl.catalyst.coop/vYYYY.MM.DD` has the right data.
- [x] Verify `s3://pudl.catalyst.coop/stable` has the right data.
- [x] Verify Zenodo draft deposition has expected data
- [x] Update Zenodo description and other metadata based on release notes / details
- [x] Manually publish the new Zenodo deposition
- [x] Update dependencies and merge the conda-forge feedstock PR: https://github.com/conda-forge/catalystcoop.pudl-feedstock/pull/18
- [x] Create a GitHub Announcement #3351 (should automate with `gh release create` command)
- [x] Update [release documentation](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/run_a_release.html) to better reflect the actual process
- [x] Create an issue template for doing a release with a task list
```

```[tasklist]
# Issues to Address
- [x] The first attempted GitHub release failed because we had `@v2` as the version for the [`gh-action-sigstore-python` action](https://github.com/sigstore/gh-action-sigstore-python/tags), and they do not tag the most recent 2.x release with a generic `v2` tag. See [this discussion](https://github.com/orgs/community/discussions/48058). I'll update and create a manual GitHub release.
- [x] Delete GitHub release associated with the failed `v2024.02.03` release. (PyPI release still remains, as does the version tag on GitHub. We could delete the tag if we want).
- [x] [Google Batch refused to kickoff](https://github.com/catalyst-cooperative/pudl/actions/runs/7770671193/job/21191124342) due to the version string being part of the Batch Job ID having disallowed characters in it (b/c of the `.` in the version string).  Simplify the `BATCH_JOB_ID` not to include the version string, just the timestamp and short hash, which will always conform to the job ID requirements.
- [x] Disable the automatic creation of a GitHub Discussion "Announcement" about the release because that failed for inexplicable reasons, saying the post category doesn't exist. (but it would be nice if this worked!)
- [x] Explicitly declare `universal_pathlib` dependency in `pyproject.toml`
- [x] Explicitly declare `packaging` dependency in `pyproject.toml`
- [x] Explicitly declare `pytz` dependency in `pyproject.toml`
- [x] Explicitly decalre `urllib3` dependency in `pyproject.toml`
- [x] Explicitly declare `requests` dependency in `pyproject.toml`
- [ ] In `pudl/extract/excel.py` do we mean to be importing the non-standard library `regex` or using the built-in Python regex library `re`? If the former, then we need to explicitly declare the `regex` dependency. If the latter we need to update that module. (added for now to reflect current situation, but should review)
- [ ] Automate the building of new release documentation on RTD if it's easy. Currently the version has to be activated manually.
- [ ] Fix the automated merging of the release tag into the `stable` branch. See #3347
- [ ] The logfile distributed with the `stable` outputs is much larger than the `v2024.02.05` outputs, because it gets copied later in the process. Seems weird/bad.
- [ ] Fix garbled `setuptools_scm` auto-generated versions on RTD release docs. Rather than citing `v2024.02.05` as the version being documented, it's shown as `2024.2.6.dev0+gdc55ddc.d20240204`
- [ ] PUDL version stamped in the database is `2023.12.2.dev685+gb922919ae` rather than `v2024.2.5`
- [ ] `pudl.__version__` on the release tag returns `2023.12.2.dev629+g0735a535c` which matches neither the version stamped in the DB nor the version tag.
```
```[tasklist]
### Zenodo Metadata Tasks
- [x] Changed title so it is not version specific so we don't have to touch it again.
- [x] Make sure all Catalyst members are listed in creators (automate!)
- [x] Update Zenodo deposition description to reflect current release (automate!)
- [x] Set correct version for Zenodo data release archive (automate!)
- [x] Set keywords for Zenodo data release archive (automate!)
- [x] Set language of Zenodo data release archive (automate!)
- [x] Zenodo PUDL repo archive: update release notes (cut-and-paste from GitHub)
- [x] Zenodo PUDL repo archive: add keywords (automate with a `.zenodo.json` file for the repo)
- [x] Zenodo PUDL repo archive: set language to English (automate with a `.zenodo.json` file for the repo)
```

**Comment by zaneselvans** [comment]
The GitHub release failed because we have `@v2` as the version for the [`gh-action-sigstore-python` action](https://github.com/sigstore/gh-action-sigstore-python/tags), which does not tag the most recent 2.x release with a generic `v2` tag. See [this discussion](https://github.com/orgs/community/discussions/48058). I'll update and... try to fix.

**Comment by zaneselvans** [comment]
@jdangerx [Google Batch refused to kickoff](https://github.com/catalyst-cooperative/pudl/actions/runs/7770671193/job/21191124342) due to the version string that's part of the Batch Job ID having disallowed characters in it (b/c of the `.` in the version string).

**Comment by zaneselvans** [comment]
RTD is still requiring the new version to be manually made "active" -- there's got to be some way to make it automatically build and activate docs for any new version?

**Comment by zaneselvans** [comment]
I'm going to reset the release tag to `v2024.02.04` and try this again. The only artifact of the failed attempt should be the PyPI release. I have:

- De-activated RTD version `v2024.02.03`
- Deleted the GitHub release associated with that tag.
- LEFT the tag (as not a release) on GitHub (so it can be correlated with the PyPI release if need be)

Now I'm making a small PR into `main` which I think should fix the Google Batch ID and `gh-action-sigstore-python` issues identified above.

**Comment by zaneselvans** [comment]
GitHub release creation failed because it couldn't find the Announcements category to create a discussion, which is baffling, since it definitely exists.

**Comment by zaneselvans** [comment]
Batch kickoff failed again because the `GOOGLE_BATCH_JOB_ID` was unset somehow.

**Comment by zaneselvans** [comment]
The bit of the `release.yml` file that was supposed to merge the tagged release into the `stable` branch

```yaml
      - name: Merge the current commmit into the stable branch
        run: |
          git config user.email "pudl@catalyst.coop"
          git config user.name "pudlbot"
          git checkout stable
          git merge --ff-only ${{ github.ref_name }}
          git push
```

failed with:

```
fatal: not in a git directory
```

I think because in that job the repo had not been checked out.

**Comment by zaneselvans** [comment]
@jdangerx there was one other thing that came up incidentally in all this which is that the `workflow_dispatch` trigger for running `ci-integration` doesn't seem to be working, and it would be useful for testing the CI environment without hitting the merge queue.
