### ISSUE TITLE
PUDL release automation improvements

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3326]
Tasks that we decided weren't critical for in #2756 but will want to do as quality of life improvements.

- [x] Compile all metadata from scratch to avoid dealing with old/new mixed API calls to pull metadata from previous release.
- [x] Generate Zenodo archive description automatically from PUDL release notes.
- [x] Rather than re-running ETL on a release tag, release data from existing successful nightly build.
- [x] Update author list (names, affiliations, ORCIDs) based on Catalyst members listed in `.zenodo.json`
- [x] Update archive keywords baesd on what's listed in `.zenodo.json`
- [x] Populate the `DocumentedBy` and `SupplementedBy` fields linking to our docs, GitHub release, and Zenodo archive of source code.
- [x] Automatically set the version of the new data release to match the PUDL release tag.
- [ ] Automatically create a GitHub issue to track approval of draft Zenodo data release.

**Comment by jdangerx** [comment]
FYI @marianneke some prior art re: release automation
