### ISSUE TITLE
Release v2024.2.6 checklist

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3360]
Full documentation of process [here](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/run_a_release.html).

```[tasklist]
## Release Checklist
- [x] set a release date & notify team
- [x] Push `v2024.2.6` tag
- [x] Verify that the GitHub (software) release has been published
- [x] Verify [`catalystcoop.pudl` PyPI (software) release](https://pypi.org/project/catalystcoop.pudl/)
- [x] Verify that [PUDL repo archive on Zenodo](https://zenodo.org/doi/10.5281/zenodo.3404014) has been updated w/ new version
- [x] Wait 6-10 hours for a successful build to complete
- [x] Verify RTD build for new version is up to date (activate new version first in [RTD admin panel](https://readthedocs.org/projects/catalystcoop-pudl/versions/))
- [x] Verify `stable` and version tag point at same git ref
- [x] Verify that RTD docs build for `stable` branch gets updated
- [x] Verify `gs://pudl.catalyst.coop/vYYYY.MM.DD` has the right data.
- [x] Verify `gs://pudl.catalyst.coop/stable` has the right data.
- [x] Verify `s3://pudl.catalyst.coop/vYYYY.MM.DD` has the right data.
- [x] Verify `s3://pudl.catalyst.coop/stable` has the right data.
- [x] Verify Zenodo draft deposition has expected data
- [x] Update Zenodo description and other metadata based on release notes / details
- [x] Manually publish the new Zenodo deposition
- [x] Review `conda-forge` packaging / dependenies and publish release
- [x] Create a GitHub Discussions Announcement (should automate with `gh release create` command, eventually)
- [x] Update [release documentation](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/run_a_release.html) to better reflect the actual process
```

```[tasklist]
### Zenodo Metadata Tasks
- [x] Make sure all Catalyst members are listed in creators (automate!)
- [x] Update Zenodo deposition description to reflect current release (automate!)
- [x] Set correct version for Zenodo data release archive (automate!)
- [x] Set keywords for Zenodo data release archive (automate!)
- [x] Set language of Zenodo data release archive (automate!)
- [x] Zenodo PUDL repo archive: update release notes (cut-and-paste from GitHub)
- [x] Zenodo PUDL repo archive: add keywords (automate with a `.zenodo.json` file for the repo)
- [x] Zenodo PUDL repo archive: set language to English (automate with a `.zenodo.json` file for the repo)
```

```[tasklist]
### Issues that we ran into
- [x] Forgot to set the billing project on the object hold command in the build script. Set temporary hold manually.
- [x] Add an item to check that `gs://parquet.catalyst.coop/` release outputs are as expected
```
