### ISSUE TITLE
Post-v2024.02.05 loose ends

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3375]
[Address prioritized issues from v2024.02.05 retro](https://github.com/catalyst-cooperative/pudl/issues/3316#issuecomment-1927997468)

```[tasklist]
### Tasks
- [ ] #3347
- [x] Replace use of `regex` with built-in `re` in `pudl/extract/excel.py` and remove 3rd party library from our dependencies.
- [x] use `-q` or `--quiet` to silence verbose terminal output when distributing data to cloud buckets
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3400
```

**Comment by zaneselvans** [comment]
Adjacent to these tasks, while doing (and re-doing) the release, it became more clear to me why many projects with date-based versions use a version string more like `vYYYY.M.x` with the `x` representing the Nth release of the month in question.

- Having the version string explicitly tied to a date guarantees collisions when working through several attempts and addressing failures.
- PyPI seems to enforce a no-leading-zeroes policy on version numbers (or I don't understand how to avoid that behavior)

So I wonder if going forward we might want to adopt the more common (but less perfectly interpretable as a date) version format? Under that system the release that finally ended up working would have been `v2024.2.3` (the 3rd release pushed out in Februrary, 2024).
