### ISSUE TITLE
Investigate other utility ownership data and use cases

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3401]
Other sources of utility ownership relations data or folks interested in the outputs:

* [EPA NEEDS](https://www.epa.gov/power-sector-modeling/national-electric-energy-data-system-needs) contains utility ownership information according to Brendan Pierpont
* [GLEIF is another set of corporate entity IDs](https://search.gleif.org/#/record/I1BZKREC126H0VB1BL91) that would be useful to hook up to FERC, EIA, EPA, etc. via Brendan Pierpont
* [LittleSis/Oligrapher](https://github.com/public-accountability/oligrapher) would like to set up a call to discuss the project.
* [CorpWatch](https://github.com/michalgm/corpwatchapi/) also followed us in response to the posts about the project so we should reach out while it's still fresh in their mind.
* @sevier / [Isaac Sevier](https://isaacsevier.com/) is a potential user
* @stephenjarvis was also interested. [Personal website](https://stephenjarvis.github.io/)
```[tasklist]
### Tasks
- [x] Reach out to LittleSis - schedule call
- [x] Reach out to GEM
- [x] Reach out to CorpWatch
- [x] Reach out to Isaac Sevier
- [x] Reach out to Stephen Jarvis
```
