### ISSUE TITLE
Create an overview doc of Ex. 21 formats/layouts

### ISSUE THREAD

**Issue by katie-lamb** [catalyst-cooperative/pudl#3447]
As a first step in the extraction process we need to scope the different formats that the Ex. 21 documents come in so we can have a better understanding of what layouts to try to extract from first. Create a document with the following:

```[tasklist]
### Tasks
- [x] Target variables and which ones we can access through each layout
- [x] Screenshots of each common layout
- [x] Rough distribution of documents to each layout
- [x] Experiment with off the shelf extraction tools
- [x] List modeling method pros and cons and create issues for model experiments to try
- [x] Create issue for extracting company name and address information from 10K's (main filing not Ex. 21)
- [ ] Figure out what the difference is between different quarters of filings. What's in the Q1 filing that is not contained in the other quarters?
```

Once we've conducted this overview, we'll have a better idea of how to create a representative sample of documents to begin extracting from, or which layout to start with.

**Comment by katie-lamb** [comment]
Began creating a google doc to track this, so far main issue is that sometimes Ex. 21 tables are within an HTML table while other times they're part of a HTML body. Even when using pandas `read_html` to read in from an HTML table there needs to be some serious reformatting to get the schema right. This might require categorizing into the different formats/schemas.
