### ISSUE TITLE
Integrate EIA860 Schedule 3.2 wind generator attributes 

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3460]
```[tasklist]
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3471
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3472
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3503
- [x] Define a normalized `core_eia860__wind_generators` table with a FK relationship back to the main `core_eia__entity_generators` and `core_eia__scd_generators` tables.
- [ ] Either create a new denormalized generator output table just for wind generators, or integrate the wind attributes with the other generator attributes in the output tables. May need a design discussion.
```

**Comment by aesharpe** [comment]
Deprioritized creating denormalized output tables.
