### ISSUE TITLE
Integrate EIA860 Schedule 3.3 Solar Generator Attributes

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3461]
```[tasklist]
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3469
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3470
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3504
- [x] Define a normalized `core_eia860__solar_generators` table with a FK relationship back to the main `core_eia__entity_generators` and `core_eia__scd_generators` tables.
- [ ] Either create a new denormalized generator output table just for solar generators, or integrate the solar attributes with the other generator attributes in the output tables. May need a design discussion.
```

**Comment by aesharpe** [comment]
Deprioritized creating denormalized output tables
