### ISSUE TITLE
Integrate EIA860 Schedule 3.4 Energy Storage Equipment Attributes

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3462]
```[tasklist]
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3485
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3487
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3506
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3536
- [ ] Either create a new denormalized energy storage output table, or integrate it with the other generator attributes in the output tables if appropriate. This may require a design / data modeling discussion.
```

**Comment by aesharpe** [comment]
Deprioritized creating denormalized output tables
