### ISSUE TITLE
Integrate EIA923 Energy Storage Operations Table

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3463]
## Design Considerations
* Does the energy storage operations table have the same format as the other "generation and fuel" tables, or does it stand alone?
* Should there be a qualifier / descriptor in the table name beyond e.g. `core_eia923__monthly_energy_storage`?  Is it `_operations`? `_generation_fuel`?
* The EIA923 energy storage tab begins appearing in 2014, but the corresponding EIA860 energy storage equipment tab only appears as of 2016. Early energy storage operations data seems only to refer to pumped storage / hydro facilities, so they may all be in the existing EIA860 generators data, but something to watch out for.

```[tasklist]
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3512
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3513
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3535
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3537
- [ ] Either create a new denormalized energy storage operations output table or integrate this data with the other generation fuel tables if appropriate. May need a design discussion.
```

**Comment by Nancy9ice** [comment]
Hello, 
I noticed the 3rd task for this has the status of 'In progress', can I take it up? Or is it already being worked on?

**Comment by aesharpe** [comment]
Deprioritized creating denormalized output tables
