### ISSUE TITLE
Integrate bulk EIA Annual Energy Outlook (AEO) data

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3464]
### Design Considerations
* For the GridLab project, we only need a small subset of the data that's part of AEO, but we'll probably find other parts that we want to extract over time, so building some reusable transformations would be useful if it's not extra work.
* We should reach out to @gschivley and @grgmiller and see what data they're currently using from AEO and whether we can prepare ourselves to share their use cases as well.
* There's annual data spanning a decade (2014-2023), but is there any reason to extract more than just the most recent version at the moment? Seems like it would be interesting to track how predictions have changed over time, but that's not what we're doing right now.

```[tasklist]
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3473
- [ ] https://github.com/catalyst-cooperative/pudl-archiver/issues/293
- [ ] #3368
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3581
- [ ] Define denormalized output tables for the extracted AEO data, if appropriate
- [ ] Integrate Table 13: Natural Gas Supply, Disposition, and Prices (Henry Hub, not by region)
- [ ] Integrate Table 15: Coal Supply, Disposition, and Price (average minemouth and delivered prices, not by region)
- [ ] Integrate Table 20: Macroeconomic Indicators
```

**Comment by zaneselvans** [comment]
We descoped the additional tables above from the initial MVP. So this is done for now.
