### ISSUE TITLE
Integrate NREL ATB data

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3465]
```[tasklist]
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3473
- [ ] https://github.com/catalyst-cooperative/pudl-archiver/issues/294
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3468
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3507
- [ ] Define a denormalized output table for the NREL ATB data if appropriate
```

**Comment by aesharpe** [comment]
Deprioritized creating denormalized output tables
