### ISSUE TITLE
Make a CSV Extractor for EIA 930 files

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl#3486]
Extract EIA 930 data into 3 raw dataframe assets: raw_eia930__balance, raw_eia930__subregion, and raw_eia930__interchange.

To do this, this PR does the following:
- refactor the extractor to grab any specified partition, not just `year` (incidentally, this will make #3451 much simpler)
- map columns for three tables
- add new `assets` to `eia930.py`

Outstanding questions for the reviewer:
- Dagster makes specifying `str|int` very complex, and we use both string and int partition types. For now, I'm getting around this by specifying a `dict` type without any particular types inside it in `extract_single_partition`, but this doesn't seem ideal. Thoughts?
- Use of assets in EIA 930 to support easier subsetting, instead of multi-assets?
- We don't typically specify dtypes on import, but these are large datasets. Should we?

```[tasklist]
### Tasks
- [x] Add DOI to `datastore.py` and run `pudl_datastore --dataset eia930`
- [x] Update working partitions to use `half` instead of `h`
- [x] Refactor extractor to take `partition` rather than `year` as the unit for parallelization of extraction
- [x] Map column name changes over time for each table
- [x] Handle `subregion` only existing 2018-2024
- [x] Handle `half_year` vs `half_years`
- [x] Fix `extractor_test.py`
- [ ] Handle mixed dtypes `str|int` in partitions and test on other extracted datasets
- [ ] Add EIA 930 form PDFs to `docs.data_sources`
```
