### ISSUE TITLE
Create a transform that reshapes the NREL ATB data into a well normalized core table.

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#3507]
```[tasklist]
### Tasks
- [x] Remove duplicate records in 2021
- [x] Standardize nulls: nulls in their PKs are actually generally `*`'s meaning they pertain to all (these mostly got wiped out during the table unstacking
- [x] figure out what the first letter of the `core_metric_key` is (currently being called `mystery_code`): de-scoped see #3576
- [x] clean up `core_metric_parameter` (which will end up being the column names)
- [x] Pivot table to include one column per `core_metric_parameter` -> three separate tbales
- [x] standardize any `core_metric_parameter` that has a difference schema over the years -> `broadcast_fcr_param_across_tech_detail`
- [x] build a lil extra table(s) with the non-IDX/non-value columns from the raw data
- [x] clean up codes and types and booleans
- [x] confirm units and add them directly into the column names. maybe add a defensive check from the `units` colunm
- [x] convert draft tables from `_core` -> `core` and add db schema
```

## Known data quirks:
* The data here is relatively generic and best used for forward-looking generic resources, but could also be used to fill data gaps.
* Both CSVs and Parquet files in the S3 bucket contain summary data. The detailed data and assumptions used in the calculations are published in a large Excel workbook with many tabs and formulas.
* Technical limitations are documented by NREL [here](https://atb.nrel.gov/electricity/2023/technical_limitations).
* Data is easily accessible via Parquet in a cloud bucket, but it resembles a lookup table more than a database table.
* “Core_metric_key” field has changed over time and is blank for some records in 2022 and earlier records. It is also not a unique identifier (due to the detailed technology column).
* are used as NAs in some columns.

**Comment by cmgosnell** [comment]
The atb data is published with one `value` column that includes the numeric data which represents many different types of data. the `core_metric_parameter` column contains information about what the `value`column represents. While the raw table is very skinny (which can be nice), we often like to make sure that each column we publish contains one type of information. The intention is to `pd.unstack` the table such that the values in the `core_metric_parameter` table become the columns.

But there are a few issues that I'm running into:

## unique "pks" include `core_metric_key` which includes sub-strings relating to the `core_metric_parameter`
You can't unstack unless you have a unique index. `core_metric_key` is a required column for a unique index - its a part of a composite primary key. But `core_metric_key` has substrings that indicate which `core_metric_parameter`

### possible solutions
* rn i have implemented a pretty simple solution of simply stripping the `core_metric_parameter` substrings from `core_metric_key`. I made a new column `core_metric_key_wo_parameter` and am using this column in the composite primary key

## annual variance in `core_metric_parameter` 
This isn't a huuuge deal but there are handful of `core_metric_parameter`'s that only show up in 2023:
![Image](https://github.com/catalyst-cooperative/pudl/assets/25487998/242828ea-35ba-4ab6-a937-b76779c29dc3)
This means that we will have columns that only have data in them in 2023.

## unstacked `core_metric_parameter` table is still very sparse

**Comment by cmgosnell** [comment]
just a followup note here on this first letter of the `core_metric_key`: we ended up fully removing the two oldest years of data because these two were the only ones that had non-unique values in the data given the set of primary keys we were expecting to be able to use #3576 

(to be fair the first letter of the core_metric_key for the newer years of data definitely still includes R where the `core_metric_case` is "Market" but.. the case == Market so we ignored this first character)
