### ISSUE TITLE
Try to run extraction of new year of FERC 1 data and document results

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl#3575]
Goal: extract 2023 FERC data into a SQLite database. Document errors and debug in preparation for the release of all 2023 FERC data.

```[tasklist]
### Tasks
- [x] Update DOI
- [x] Update working partitions
- [x] Update fast and full ETL settings
- [x] Run datastore locally to cache new files
- [x] Run `ferc_to_sqlite` fast ETL (2022 and 2023 Form 1)
- [x] Update taxonomy in Ferc1XbrlToSqliteSettings to Q4 Form 1 taxonomy: https://ecollection.ferc.gov/taxonomy/form1/2023-11-01/form/form1/form-1_2023-11-01.xsd
- [x] Run just 2023 FERC Form 1 data through `ferc_to_sqlite`
- [ ] Document and debug errors
```
#### `messageCode` not found
```
Message: Try #0: taxonomy_source=<arelle.FileSource.FileSource object at 0x72145bf66a20>  
Message log error: Formatting field not found in record: 'messageCode'
```

#### Publication Time KeyError during XBRL extraction

One company that has not yet filed 2023 data appears to be causing a key error issue. Another company that _has_ filed 2023 Q4 data seems to cause the same key error when just running 2023 data.

KeyError: 'Rochester_Gas_and_Electric_Corporation_form1_Q4_1682080397.xbrl' - not filed
KeyError: 'Lockhart_Power_Company_form1_Q4_1711466566.xbrl' - filed

```
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "ferc1_xbrl"::
KeyError: 'Rochester_Gas_and_Electric_Corporation_form1_Q4_1682080397.xbrl'

  File "/home/.../miniforge3/envs/pudl-dev/lib/python3.12/site-packages/ferc_xbrl_extractor/instance.py", line 471, in get_instances
    return instances_from_zip(instance_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../miniforge3/envs/pudl-dev/lib/python3.12/site-packages/ferc_xbrl_extractor/instance.py", line 433, in instances_from_zip
    publication_time=publication_times[filename],
```

**Comment by jdangerx** [comment]
We tried, we found issues, ensuing work will be tracked as sub-tasks of #3544.
