### ISSUE TITLE
Transform high-priority AEO Table 54 data into normalized assets

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3581]
Table 54 has heterogeneous data with a variety of different units, so we'll have to pull those out into multiple different assets.

The first set of data we want to pull out of Table 54 is all the data that's in gigawatts. That will be two assets, one with electricity sector data and one with end-use sector data.

Electricity sales data is also high-priority.

For each, we need to subset the raw table 54 data, transform it into a table with one column for each variable, and then persist it to the database.

These are the high priority resources we need to create:

```[tasklist]
# Resources
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3596
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3597
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3607
```
