### ISSUE TITLE
Summer 2024 major dependency updates

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3605]
We expect to see some major / breaking releases to these core dependencies this Spring & Summer

```[tasklist]
- [x] Update to Geopandas v1.0
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3736
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3735
```
