### ISSUE TITLE
Update DOI automatically for well-behaved datasets

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3639]
### Overview

We don't update the DOI reference immediately upon publishing a new archive, because oftentimes using a new version of a dataset causes problems. Instead we wait until we have manually checked all the new differences. This is time-consuming and unnecessary for some datasets.

### Success Criteria

How will we know that we're done?

* [ ] Pull requests made automatically when we see new DOIs for `eia930`, `eia_bulk_elec`, `eia860m`, and `epacems`
* [ ] PRs tag someone for review
* [ ] We have clear criteria written down for approving these PRs

### Tasks
What are the next steps to take?

```[tasklist]
* [ ] write a PR template that includes instructions for PR approval
* [ ] write a GH action that detects new DOIs and makes PRs accordingly
```

**Comment by zaneselvans** [comment]
I'm not sure EIA-860M belongs in this list (sorry if I'm the one that mentioned it!) since it's where we'll first see new EIA plants that need to be manually mapped to PUDL Plant IDs.

**Comment by jdangerx** [comment]
Yeah, that makes sense! I just copied over your list from the original issue but obviously happy to change that 😄
