### ISSUE TITLE
Add the FK relationship to the new EIA860 storage direct support plant/generators

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#3695]
There are new sets of plant_id's and generator id's in the `core_eia860__scd_generators_energy_storage` table which are all about whether a storage generator supports another generator. Goal of this issue is to add these new id's into special FK relationships. It is possible that we will need to harvest these new ID's in order to actually have all of the ID's in the harvested generators table. Another possible barrier is that there definitely nulls in these columns. Is it okay to have nulls in a column with a foreign key relationship to a table that doesn't have any nulls?

These are the columns at question:
```
"plant_id_eia_direct_support_1",
"generator_id_direct_support_1",
"plant_id_eia_direct_support_2",
"generator_id_direct_support_2",
"plant_id_eia_direct_support_3",
"generator_id_direct_support_3",
```
Running `pudl_check_fks` without the new alembic schema produces the following errors:
```
pudl.etl.check_foreign_keys.ForeignKeyErrors: Foreign key error for table: core_eia860__scd_generators_energy_storage -- core_eia__entity_generators (plant_id_eia, generator_id, plant_id_eia, generator_id, plant_id_eia, generator_id) -- on rows [1523 1548 1576 1589 1596 1727 1728 1795 1796 1827 1864 1865 1879 1892
 1895 1909 1920 1922 1934 1943 1946 1977 2028 2046 2059 2069 2088 2101
 2102 2105 2108 2109 2110 2111 2112 2116 2125 2126 2133 2143 2224 2236
 2315 2316 2317 2408 2448]
```

Which have the following values:

|      | plant_id_eia_direct_support_1 | generator_id_direct_support_1 | plant_id_eia_direct_support_2 | generator_id_direct_support_2 | plant_id_eia_direct_support_3 | generator_id_direct_support_3 |
|-----:|------------------------------:|------------------------------:|------------------------------:|------------------------------:|------------------------------:|------------------------------:|
| 1523 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1548 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1576 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1589 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1596 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1727 |                       62975.0 |                         SYNLB |                           NaN |                          None |                           NaN |                          None |
| 1728 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1795 |                       63490.0 |                           WIL |                           NaN |                          None |                           NaN |                          None |
| 1796 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1827 |                       64185.0 |                         DRAPV |                           NaN |                          None |                           NaN |                          None |
| 1864 |                       64436.0 |                           WLB |                           NaN |                          None |                           NaN |                          None |
| 1865 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1879 |                       64520.0 |                          SOL1 |                           NaN |                          None |                           NaN |                          None |
| 1892 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1895 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1909 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1920 |                       64852.0 |                         DAGGB |                       64852.0 |                         DAGGP |                           NaN |                          None |
| 1922 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1934 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 1943 |                       65055.0 |                         77FPV |                           NaN |                          None |                           NaN |                          None |
| 1946 |                       65058.0 |                         WAIBA |                       65058.0 |                         WAIPV |                           NaN |                          None |
| 1977 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2028 |                       66076.0 |                         20409 |                           NaN |                          None |                           NaN |                          None |
| 2046 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2059 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2069 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2088 |                       67457.0 |                         SHPV1 |                           NaN |                          None |                           NaN |                          None |
| 2101 |                       61169.0 |                         60798 |                           NaN |                          None |                           NaN |                          None |
| 2102 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2105 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2108 |                       61720.0 |                            30 |                           NaN |                          None |                           NaN |                          None |
| 2109 |                       61722.0 |                            32 |                           NaN |                          None |                           NaN |                          None |
| 2110 |                       61752.0 |                            49 |                           NaN |                          None |                           NaN |                          None |
| 2111 |                       61807.0 |                            66 |                           NaN |                          None |                           NaN |                          None |
| 2112 |                       62494.0 |                         SCSOL |                           NaN |                          None |                           NaN |                          None |
| 2116 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2125 |                       63541.0 |                         63257 |                           NaN |                          None |                           NaN |                          None |
| 2126 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2133 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2143 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2224 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2236 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2315 |                       65550.0 |                         64921 |                           NaN |                          None |                           NaN |                          None |
| 2316 |                       65550.0 |                         65789 |                           NaN |                          None |                           NaN |                          None |
| 2317 |                       65550.0 |                          None |                           NaN |                          None |                           NaN |                          None |
| 2408 |                           NaN |                          None |                           NaN |                          None |                           NaN |                          None |
| 2448 |                       67282.0 |                          5654 |                           NaN |                          None |                           NaN |                          None |

```[tasklist]
### Tasks
- [x] Add new `foreign_key_rules` into `core_eia__entity_generators` for each of  these direct support column names for the plant/gen ids. (examples of other tables that do this are: `core_eia__entity_utilities`, `core_eia860__scd_utilities`)
- [x] Regenerate the alembic schema
- [x] test the relationships w/ `pudl_check_fks`
- [x] fix plant ID dtypes
- [x] Rule out incorrectly written string nulls in SQLite DB by directly querying in DB Browser
- [x] debug NaNs / Nones failing the FK check
```

**Comment by e-belfer** [comment]
When running just on the `direct_support_1`:

[1523 1548 1576 1589 1596 1727 1728 1795 1796 1827 1864 1865 1879 1892
 1895 1909 1920 1922 1934 1943 1946 1977 2028 2046 2059 2069 2088 2101
 2102 2105 2108 2109 2110 2111 2112 2116 2125 2126 2133 2143 2224 2236
 2315 2316 2317 2408 2448]

**Comment by e-belfer** [comment]
When I attempt to harvest by adding the plant and generator ID fields to `mapped_schemas` [here](https://github.com/catalyst-cooperative/pudl/pull/3699/files#diff-df43cc581de4fd543312acfbe88e09a3aa8772c301f880fe104cbd98c672b14e), I get the following error for both the plants and generators entity tables:

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "harvested_plants_eia":

  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 501, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 186, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 91, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 195, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 164, in _yield_compute_results
    for event in iterate_with_context(
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 466, in iterate_with_context
    with context_fn():
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 84, in op_execution_error_boundary
    raise error_cls(

The above exception was caused by the following exception:
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comp/Desktop/Catalyst/PUDL/pudl/src/pudl/transform/eia.py", line 1275, in harvested_entity
    entity_df, annual_df, _col_dfs = harvest_entity_tables(
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comp/Desktop/Catalyst/PUDL/pudl/src/pudl/transform/eia.py", line 529, in harvest_entity_tables
    compiled_df = _compile_all_entity_records(entity, clean_dfs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comp/Desktop/Catalyst/PUDL/pudl/src/pudl/transform/eia.py", line 417, in _compile_all_entity_records
    compiled_df = pd.concat(dfs, axis=0, ignore_index=True, sort=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 395, in concat
    return op.get_result()
           ^^^^^^^^^^^^^^^
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 680, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comp/miniforge3/envs/pudl-dev/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3885, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)

**Comment by e-belfer** [comment]
Adding these IDs to the harvesting process seems to have fixed the issue, and `pudl_check_fks` is now passing on #3699.
