### ISSUE TITLE
Asset check failures do not fail integration tests

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3705]
### Overview

@cmgosnell found out that asset check failures appear to not fail integration tests, even if they have `blocking=True` set - she also found that there are no `fgd_equipment_null_cols` or `cooling_equipment_null_cols` checks even being run in the CI logs here: https://github.com/catalyst-cooperative/pudl/actions/runs/9570342720/job/26384880686.

We should probably fix this.

### Success Criteria
* [ ] if an asset check fails in `etl_fast` it should stop integration tests from passing

```[tasklist]
### Tasks
- [x] make a bunch of asset checks fail and see that it doesn't blow up the integration tests
- [x] ... fix it
- [x] make a bunch of asset checks fail and see that it *does* blow up the integration tests
```
