### ISSUE TITLE
2024Q2 Quarterly Updates

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#3758]
### Quarterly Update Check-list

Once the new archives have been vetted and published, you can begin the process of integrating the new quarterly update data into PUDL.

Follow the steps in [Existing Data Updates Docs](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/existing_data_updates.html)

```[tasklist]
### Tasks
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3760
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3762
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3763
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3777
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3761
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3759
- [ ] https://github.com/catalyst-cooperative/pudl/pull/3790
```

**Comment by zaneselvans** [comment]
There were some [minor error corrections to the 2024 NREL ATB](https://atb.nrel.gov/electricity/2024/errata) that we should probably include in this update -- I think it should be as easy as updating the DOI.

**Comment by zaneselvans** [comment]
Almost all of the FERC archives seem to have grown a tiny bit since July, so I tried updating the DOIs and running the ETL in #3790 which doesn't seem to have caused any ETL issues.
