### ISSUE TITLE
Release v2024.8.0 Checklist

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3800]
[Additional release process documentation](https://catalystcoop-pudl.readthedocs.io/en/nightly/dev/run_a_release.html).

```[tasklist]
## Release Checklist
- [x] Set a release date & notify team
- [x] Close out the [PUDL Release Notes](https://catalystcoop-pudl.readthedocs.io/en/nightly/release_notes.html) with an overview of the changes in this release
- [x] Create and push `v2024.8.0` tag
- [x] Verify that the new [GitHub (software) release](https://github.com/catalyst-cooperative/pudl/releases) has been published
- [x] Verify [`catalystcoop.pudl` PyPI (software) release](https://pypi.org/project/catalystcoop.pudl/)
- [x] Verify that [PUDL repo archive on Zenodo](https://zenodo.org/doi/10.5281/zenodo.3404014) has been updated w/ new version
- [x] Wait 6-10 hours for a successful build to complete
- [x] Activate new version on the [RTD admin panel](https://readthedocs.org/projects/catalystcoop-pudl/versions/) and verify that it builds successfully.
- [x] Verify that `stable` and the version tag point at same git ref
- [x] Verify that [`stable` docs on RTD](https://catalystcoop-pudl.readthedocs.io/en/stable/) have been updated
- [x] Verify `gs://pudl.catalyst.coop/vYYYY.M.x` has the new expected data.
- [x] Verify `gs://pudl.catalyst.coop/stable` has the new expected data.
- [x] Verify `gs://parquet.catalyst.coop/vYYYY.M.x` has the new expected data.
- [x] Verify `gs://parquet.catalyst.coop/stable` has the new expected data.
- [x] Verify `s3://pudl.catalyst.coop/vYYYY.M.x` has the new expected data.
- [x] Verify `s3://pudl.catalyst.coop/stable` has the new expected data.
- [x] Verify that draft deposition for [this Zenodo archive](https://doi.org/10.5281/zenodo.3653158) has the new expected data
- [x] Update Zenodo description and other metadata based on release notes (see task list below)
- [x] Manually publish the new Zenodo deposition with the updated metadata
- [x] Create an Announcement for the release in [our GitHub Discussions](https://github.com/orgs/catalyst-cooperative/discussions)
- [x] Update the [release documentation](https://catalystcoop-pudl.readthedocs.io/en/nightly/dev/run_a_release.html) to better reflect the actual process for next time
- [x] Wait 2-12 hours for a bot to create a PR in the [PUDL conda-forge feedstock](https://github.com/conda-forge/catalystcoop.pudl-feedstock/pulls)
- [x] Review the `conda-forge` PR, updating dependencies and CLI entrypoints if necessary. Our direct dependencies (from `pyproject.toml`) should be pinned to the actual version appearing in `environments/conda-linux-64.lock.yml`
```

```[tasklist]
### Zenodo Metadata Tasks
- [x] Make sure all Catalyst members are listed in creators (automate!)
- [x] Update Zenodo deposition description to reflect current release (automate!)
- [x] Set correct version for Zenodo data release archive (automate!)
- [x] Set keywords for Zenodo data release archive (automate!)
- [x] Set language of Zenodo data release archive (automate!)
- [x] Zenodo PUDL repo archive: update release notes (cut-and-paste from GitHub)
- [x] Zenodo PUDL repo archive: add keywords (automate with a `.zenodo.json` file for the repo)
- [x] Zenodo PUDL repo archive: set language to English (automate with a `.zenodo.json` file for the repo)
```

```[tasklist]
### Issues that we ran into
- [x] Our CITATIONS.cff file was way out of date. It should be updated as part of each release.
- [x] Add keywords, language, and list of creators to a new `.zenodo.json` file in the repo.
- [ ] The version strings displayed prominently on RTD are a mess for tagged versions see #3425
- [ ] Generated release notes went allll the way back, instead of just diffing vs. the last tagged release.
- [ ] The `conda-forge` bot isn't detecting our new release automatically, and the bot command also didn't work.
```

**Comment by zaneselvans** [comment]
For some reason the autogenerated release notes (which end up on the GitHub release page and also on the archive of the repo on Zenodo) didn't just look at changes since the last release, and included years worth of changes.  I don't think this happened last time, and I don't see anything about how to specify the range of PRs/commits/dates that get included in [the documentation](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).  I went in and manually deleted all the old cruft, but seems like this is wrong.
