### ISSUE TITLE
Write transform function to clean and normalize FERC 714 XBRL hourly historic load table

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#3838]
```[tasklist]
### Tasks
- [x] decide if/how to use pieces of the form 1 transforms (https://github.com/catalyst-cooperative/pudl/issues/3809#issuecomment-2344445336)
- [x] pull relevant methods out of transform.ferc1/classes  into more accessible functions
- [x] pull both csv and xbrl files into one asset
- [x] pull csv-based transform code out of existing transform function into their own modular functions
- [x] prep duration_xbrl: (convert the yearly reported records)
- [x] prep instant_xbrl: nada
- [x] prep xbrl: SO MUCH TIME SERIES CLEANING. objective: complete, continuous, non-duplicative datetime64[ns]
- [x] document small number of gaps in xbrl (mostly from daylight savings time hour)
- [x] prep csv: migrate csv-only relevant code into csv step
- [x] map_respondent_id_ferc714: csv/xbrl -> PUDL id (first phase done in #3846)
- [x] concatenate CSV + XBRL
- [x] deduplicate time series
- [x] map new bad utc offset codes
- [x] plot all respondents and do major spot fixing/timezone fixing
- [ ] [maybe] rename this table from `out_` to `core_`?
- [x] add the respondent_id_ferc714_csv and respondent_id_ferc714_xbrl into the table schema
- [x] add the #3846 little glue respondent id tables into db
- [x] back/forward fill the source respondent ids
- [x] add any additional info about the table into the metadata
- [x] sort the table before loading to make it most efficient for parquet
- [x] release notes
- [x] run all of the downstream analysis outputs
```

### out of scope here -> issue or pr or otherwise
- make the extract loading wayyyy faster or skip it for this hourly table -> dealing w/ this in #3861

**Comment by cmgosnell** [comment]
should we add the `respondent_id_ferc714_csv` and `respondent_id_ferc714_xbrl` into the table schema?

because this hourly table is a parquet table not a db table it doesn’t really have foreign key relationships to these soon to be small glue tables the stores the map between the pudl-derived ids and these new ids. i assume most users will primarily be familiar with or searching for a utility with one of these _{source} native IDs.

but adding theee two columns into an already very large table (when one will always be null) is not the tidiest

**Comment by cmgosnell** [comment]
re plotting the demand timeseries, here are a few things I did. Nothing hugely bad jumped out at me tbh.
* plot full timeseries for all respondents - done with new pudl-derived respondent ids to see if there were weird disjointed things that would maybe indicate we mapped the ID's incorrectly. i was also looking for new weird big missing bits or new trends that were real different from the past. I did find a good handful of big gaps and periods where the demands was suddenly higher or lower in the CSV years but i'm assuming that's oos for this work
* plot 2019-now for all respondents: looking for similar oddities about the 
* plot one month at a time. i tried a few months separately all from the new data. mostly for this one i was looking for phase shifts that could indicate that we got the timezone wrong. believe it or not nothing jumped out at me. I was mostly looking for which hour the peaks happened... this felt very unscientific I bet we could find some other way to do this more 


fully_empty = [42,47, 48,175,180,31, 97]
big_spikes = [19,161, 77]
long_big_spikes = [16]

this is my little code snippet that i used for plot things.. this is the most complicated one so you can remove specific pieces of the mask to expand it
```python
for rid in df.respondent_id_ferc714.unique():
    recent = df[(df.respondent_id_ferc714 == rid) & (df.datetime_utc.dt.month == 5) & (df.datetime_utc.dt.year == 2022)]
    if not recent.empty or recent.demand_mwh.notnull().any():
        recent.sort_values("datetime_utc").plot("datetime_utc", "demand_mwh", title=f"Respondent ID {rid}")

        plt.show()
```


## some examples
these are not super helpful on their own but you get the gist
all time:
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/c6d361c8-5984-4a16-8ac0-48c73fb5908f">
recent years:
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/f5cb79fe-2ade-45b4-aa12-92b342866c20">


one month:
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/78c97b40-d99e-46d7-9c68-ae456dd8cd18">
