### ISSUE TITLE
Write transform function to clean and normalize FERC 714 XBRL respondent ID table

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#3839]
```[tasklist]
### Tasks
- [ ] ensure no sructural changes in new and old data
- [ ] do id's change year-to-year?
- [ ] are there new id's that are different than the old ids?
- [ ] fix any baddies
```

**Comment by zaneselvans** [comment]
One thing I've noticed looking at the old and new data for this table, is that the XBRL derived data looks like a combination of 2 tables in the DBF/CSV data, and some of the additional data might be helpful for doing record linkage. So we might want to look at bringing in the 2nd identification / certification data table from the DBF data, which would allow better continuity between the XBRL & CSV data.
