### ISSUE TITLE
Prepare for first round of Superset user testing

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3855]
Now that we've received Catalyst feedback on the superset UX and checked in, we're ready to do some user testing! Before we actually start conducting interviews we need to answer some questions:
- What user improvements do we want to make before user testing?
- What are our primary questions for users? 
- How do we want to conduct the user interviews? Async?
- Who do we want to reach out to? What types of users do we want to test this on?
```[tasklist]
### Tasks
- [x] Research a general framework for conducting synchronous UX testing
- [x] Find a couple of Catalyst Cats who would be willing to conduct the interviews starting October 7
- [x] Create a calendar signup
- [x] Create a list of people to reach out to
- [x] Create a list of questions we want to ask users
- [x] Test out user testing on a Catalyst Cat
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3867
```

**Comment by bendnorman** [comment]
Ella and I chatted about these questions and came up with some [answers](https://docs.google.com/document/d/1tj-aVwGSh2KhExRFV9AtewRAbENtePHp3iTvykXVGUE/edit#heading=h.dq7awc6j6m)!

What are the success criteria for Superset? What do we want to test?
- People can make an account and it has the correct permissions by default
- People can get to the welcome dashboard easily or redirected
- Welcome dashboard points them to the tool that suits their use case
  - Download data as csv without exceeding row limits
  - Create a chart from an existing dataset
  - Doing some SQL queries on it, can you create a chart from the query?
- Can they find the data their are looking for
- What is your typical workflow in datasette. How would you do this in superset?
- Can you share a chart with a colleague?
- Can you download data for X thing using Y filter?
- Can you create a specific chart? "yearly net generation by fuel type in TX"
