### ISSUE TITLE
VCE Renewable Generation Dataset Integration

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#3872]
### Description
This epic coordinates the integration of the Vibrant Clean Resource Adequacy Renewable Energy Power Datasets. It contains estimated county-averaged hourly capacity factor for wind and solar generating facilities in the US from 2019 through 2023. 

This data is similar to the `gridpathtoolkit` capacity factor data, but it's calculated using different methodology and is published at different granularities. Part of the project scope includes comparing the two data sources.

Review the [dataset overview](https://vibrantcleanenergy.com/wp-content/uploads/2020/08/VCE-Weather-Dataset-Overview_August2020.pdf) and the [methods used create this dataset](https://vibrantcleanenergy.com/wp-content/uploads/2021/04/2018%20VCE%20Study_Dataset%20Methods%20and%20Analysis536960.pdf).

This dataset is currently proprietary. 

**Data source moniker:** `vcerare`

### Motivation
This project is funded by Vibrant Pattern Futures (Pattern Energy + Vibrant Clean Energy) to ensure that the dataset be programmatically verified and made easily accessible to the public. 

### Scope
View our [SOW document](https://docs.google.com/document/d/1BWe9zJZStzWjx13_yDtpQ1FsxsTYBWTdFphkJ6JRSP0/edit) and [hours estimations](https://docs.google.com/spreadsheets/d/1SL2EjB2C4eMLzLotMe6nmlvcgDtJE7Rdrbys4e9RhNc/edit?gid=0#gid=0).

```[tasklist]
# Tasks
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3886
- [ ] https://github.com/catalyst-cooperative/pudl/pull/3897
- [ ] https://github.com/catalyst-cooperative/pudl-archiver/issues/434
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3880
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3874
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3876
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3877
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3875
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3878
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3879
- [x] Updates docs to link directly to parquet file
- [x] Respond to any feedback from VCE
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3891
```

**Comment by zaneselvans** [comment]
In the licensing agreement Chris asked that the dataset be attributed to VCE, so I think it should probably be `vceregen`

**Comment by aesharpe** [comment]
Chis noted in his email a few days ago that his preferred moniker is `vcerare` standing for Resource Adequacy Renewable Energy, so I'm going to use this moving forward.

**Comment by aesharpe** [comment]
There are still some memory issues to work through with this dataset, but the tasks themselves are complete.
