### ISSUE TITLE
Investigate source of fill bug + propose some potential fixes

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#3889]
On June 18th 2024, we received a question about some notably high values in the `out_eia923__fuel_receipts_costs` table. This was resulting in anomalously high fuel prices in some cases, identified first in deliveries of BIT to plants with plant_id_eia `8102` and `2832`.

These values were not present in `core_eia923__monthly_fuel_receipts_costs`, and it turns out that the error was introduced on our end. In #3716, we turned off the rolling average behavior, which affected about 2% of records in `out_eia923__fuel_receipts_costs`. This is distinct from the values filled from the bulk electricity data.

# Part 1: Diagnose the problem

Success criteria: Identify what section of the code created the incorrectly calculated values, and whether `out_ferc1__yearly_steam_plants_sched402` is also affected.

It's not clear whether the issue is resulting from the filling step, or the calculation of the rolling averages. If it's in the calculation of the rolling averages, then the `out_ferc1__yearly_steam_plants_sched402` table could also be affected, as the same routine is used there to calculate a smoothed estimate of ongoing capital additions.

```[tasklist]
- [x] Download nightly build data from June 18.
- [x] Regenerate the problematic `out_eia923__fuel_receipts_costs` with the rolling behavior turned off, and compare outputs using the code snippet in #3716
- [x] As part of your diagnostic process, write a series of unit tests for `pudl.helpers.fillna_w_rolling_avg()` and `pudl.helpers.generate_rolling_avg()` that make sure the function is behaving as expected and diagnose any potential behavioral failures
- [x] Identify whether the divergence occurs in `pudl.helpers.fillna_w_rolling_avg()` or `pudl.helpers.generate_rolling_avg()`, and what line of code is the source of the problem
- [x] Assess whether the `out_ferc1__yearly_steam_plants_sched402` is also affected by the same problem. (it totally was affecting the capital additions as well... it had a window of 3 so there were less records effected overall but still :grimacing:
```

# Part 2: Design and implement a solution
Success criteria: Decide whether to re-implement the rolling average behavior. If so, identify any necessary code changes and implement them.

If we want to turn this back on, we'll need to not only understand what the problem was, but also to understand how to fix it.
```[tasklist]
- [x] Once the problem is diagnosed, propose a new design for a rolling average or assess the scale of data that would be left unfilled if we leave this off
- [ ] Add a 'filled' flag to enable quick determination of whether the affected columns (e.g., `fuel_cost_per_mmbtu`) are filled for downstream users.
```

**Comment by cmgosnell** [comment]
some preliminary poking:
![Image](https://github.com/user-attachments/assets/9b9a09a3-d06f-4e2f-83bd-72a2fe9e5c27)

okay... this graph is a little chaotic but I've determined that this fill is borking when there are different energy_source_code's in the table. The last few BIT records are looking more like the DFO records. When I add in the `"supplier_name","mine_name"` into the `group_cols` I do not see the averaging of the BIT and DFO costs:

![Image](https://github.com/user-attachments/assets/c60057e0-9e90-4c18-a840-9f1f928e5451)
 
i also don't see the DFO cost roll-filling. Which is good because there isn't enough records of DFO to create a monthly 6-month rolling window.

**Comment by cmgosnell** [comment]
okay fixing the problem using the groupby.rolling looks like this:
![image](https://github.com/user-attachments/assets/b8815c5d-0c87-4065-97a3-2458f1af2bc1)
