### ISSUE TITLE
Refactor VCE RARE asset checks

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3926]
```[tasklist]
### Tasks
- [x] Review asset checks and see if their memory footprint can be reduced
- [x] Remove any asset checks that seem low value and resource intensive
- [x] Accumulate an error report and return it if any of the piecemeal checks fail
- [x] Fix the expected row-count asset check so that it can pass in the fast ETL (#3993)
```

**Comment by zaneselvans** [comment]
Most of these issues were addressed in #3959 but the row-count check still only passes if all data is processed, meaning the `fast_etl` will always fail if asset checks are enabled, which they should be.
