### ISSUE TITLE
Expand FERC 1 data validation to include 1994-2018

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#464]
Now that all the remaining FERC 1 data has been nominally integrated (See #286, #344), it needs to be validated. An initial run of the data validation tests yields at least the following data validation issues to explore:

## fuel_ferc1:
* [x] oil costs per unit burned are out of bounds possibly due to gallons to barrels conversion, see issue #489
* [x] coal costs per unit burned are out of bounds too low, due to lack of mmbtu to tons unit conversion. See #489

## plants_steam_ferc1:
* [x] Plant hours connected to load has a bunch of weird > 8784 hour values. See issue #488 

## plant_in_service_ferc1:
* [x] 11575 duplicate `record_id` values in `plant_in_service_ferc1` -- this is expected (because of the row-unpacking), but that should be accounted for somehow.

## purchased_power_ferc1:
* [x] 6 duplicate `record_id` values in `purchased_power_ferc1` which is unexpected, since there's no row unpacking happening there. These are honest-to-god duplicate rows, across all columns, which should not be here at all -- Will call `drop_duplicates()` in transform step to clean them out.

## fbp_ferc1:
* [x] `fbp_ferc1_gas_price_distribution` and `fbp_ferc1_coal_price_distribution` are failing with out of bounds values.

## miscellaneous tests:
* [ ] Mysteriously, the duplicate years in plant ID FERC 1 is no longer failing (???)
* [ ] Similarly, mysteriously the FERC 1 vs. PUDL Plant ID Clash test is no longer failing (???)
