### ISSUE TITLE
Set up pudl python packaging for installation

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#63]
Once we have the code stabilized, we need for folks to actually be able to install the package on their own machine.  This will require a work with setup.py and name spaces/import clean up. This is a... meta-issue, with lots of related sub-issues:
* [x] #331 Move all files to be distributed as package resources into the python package `src` directory.
* [x] #326 Implement automated testing of packaging and installation using Tox.
* [ ] #320 Allow users to specify their own PUDL input and output directories.
* [ ] #327 Turn standalone scripts into modules with entry points.

**Comment by zaneselvans** [comment]
Closing this issue because it has been functionally replaced by the Packaging & Release project as a whole, which breaks this task down into many smaller pieces.
