### ISSUE TITLE
Review all the documentation for correctness / formatting etc. for a 0.4.0 release

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#694]
**[Proposed documentation tree on Google Drive](https://docs.google.com/document/d/1hBWSpBARpr27rcR4ongK4RgZ-Fhi0T99IpuMwvtUPyY/edit)**

## GENERAL
- [ ] Remove any irrelevant or confusing pages.
- [ ] Consolidate related pages.
- [ ] Update flow of pages so it's clear what information users need and when.

## README.md / Front page
- [ ] @cmgosnell first pass
- [ ] @aesharpe  Edit

## Usage
- [x] @cmgosnell Write a first draft
- [ ] @zaneselvans review
- [x] @aesharpe review
- [ ] Update to reflect using an archive Docker image + data for access. 
- [x] Include link to development setup instructions (i.e. running ETL locally)

## PUDL High Level Overview
- [x] @aesharpe first pass
- [ ] @zaneselvans review
- [x] @cmgosnell review

## Data Source Specific Pages
@aesharpe will do a first pass
- [x] #906 Investigate publishing the table metadata
- [x] #938 Update transform module doc strings to include description of transformations.
- [x] Add top level data source landing page
- [ ] #832 EIA861 docs page
- [x] #833 EIA860 docs page
- [x] #834 EIA923 docs page
- [x] #835 FERC1 docs page
- [x] #836 EPA CEMS docs page
- [ ] Relate PUDL tables to OG source tables - add notes to [template](https://docs.google.com/document/d/1VapazxD0dC7A4hMjApBuTI5rMupqltwSTqbkcMUIi70/edit#heading=h.ofklo9eq7x7i) document.

## Contributing
- [ ] @zaneselvans do a first pass.

## Development Documentation
- [x] @zaneselvans first pass
  - [x] Dev environment setup
  - [x] Testing & data validation
  - [ ] Integrate old usage / ETL docs for pudl_setup and pudl_etl
  - [ ] Project and Branch Management / GitHub workflow
  - [ ] Dependencies & Python Packaging
- [ ] @aesharpe review
- [ ] @cmgosnell review
