### ISSUE TITLE
Re-integrate 88888 and 99999 data to eia861

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#808]
Found and re-purposing this old issue. It was closed, but the 88888 and 99999 values were still getting dropped 🤷‍♀ .

# Description
Many years ago, when we first integrated the EIA 861 data, we came across rows with `88888` and `99999` in the `utility_id_eia` field for several tables. 

**What are these rows?**
- `88888` = Information for utilities who's identifying information has been redacted for privacy reasons. Each row represents an individual utility. 

- `99999` = State-level adjustment values added by EIA that account for capacity lost in conversion from DC to AC. These values are negative, and do not represent reported values from an individual utility.

**In what tables do these rows appear?**
- `88888`
     - **Demand Side Management** (one utility from 2010 - 2012)
     - **Sales** (one utility from 2008 - 2023)
     - **Utility Data** (nine utilities from Texas from 2009 - 2023)
     - **Operational Data Revenue** (nine utilities from Texas from 2008 - 2023)
     - **Balancing Authority** (one utility from 2010 - 2011, two in 2012)
     - **Dynamic Pricing** (one utility from 2020 - 2023)
     
- `99999`
     - **Sales** (one per year/state/ba_code/customer_class/service_type/business_model from 2001-2023)
          - A state, service type, and balancing authority-level adjustment is made for non-respondents and for customer-sited respondents.
     - **Non Net Metering** (one per year/state/ba_code from 2018-2023)
          - We make a state-level adjustment for missing PV capacity and to convert state total capacity to AC units for those respondents who report data in DC units; we use 0.8256 as a conversion factor to change DC to AC. For other energy sources, we have not established imputation procedures
     - **Net Metering** (one per year/state/ba_code from 2018-2023)
          - We make a state-level adjustment for missing PV capacity and to convert state total capacity to AC units for those respondents who report data in DC units; we use 0.8256 as a conversion factor to change DC to AC. For other energy sources, we have not established imputation procedures
     - **Advanced Metering Infrastructure** (one per year/state/ba_code from 2020-2023)
          - Unclear how these 99999 values are calculated for `non_amr_ami` (Number of non-AMR/AMI meters)....
     - **Balancing Authority** (we can remove these because there is no useful data here. I think they get introduced via PUDL, not the raw data).

**We removed most of these values from the tables they appeared in because:** 
- `88888` values were not unique primary keys
- `99999` values were not the same type of data as the rest of the table (a utility)

In the interest of preserving as much of the original data as possible, we think it's appropriate to re-integrate these values where they appear in the raw data. There are several caveats and re-integration methods to consider.

# Possible Solutions

`99999`: Because these values don't complicate the primary key, it's pretty easy to just re-integrate them when there are values that aren't NA. We don't have to build any work-arounds.

`88888`: These values are more complicated because they interfere with the primary key. However, there are only two tables with more than one `88888` value per year. 
- **Option 1**: Add another primary key column to distinguish `88888` values.
     - PRO: preserve data granularity
     - CON: add a column that is mostly NA
- **Option 2**: Aggregate `88888` values by the primary key.
     - PRO: ease of use by users, no primary key issues
     - CON: lose data granularity, need to explain aggregation somewhere.
- **Option 3**: Rename `88888` values to distinguish them
     - PRO: solves primary key issue
     - CON: can't be consistent year over year with rename, not as searchable.

We met as a team and decided that **Option 2** is the best for now.
     
# To-Do

**Re-integrate `99999`**
- [ ] Remove all references to removing `99999` rows from eia861
- [ ] Remove `99999` values from tables where all rows are NA -- this is a product of our normalization process and table splitting.
- [ ] Add usage warning in table description explaining `99999` rows.

**Re-integrate `88888`**
- [ ] Remove all references to removing `88888` rows from eia861
- [ ] Write a function to aggregate `88888` rows by the primary key and integrate it into the relevant tables where this is expected. Make sure primary key would check would fail on tables otherwise (so we can see if this happens in the future).
- [ ] Add a usage warning to the table description explaining the aggregated rows.

**Comment by aesharpe** [comment]
Problem with **Option 2** -- Some of the tables we are planning to aggregate 88888 values from contain non-numerical content that is difficult aggregate. For example, the `core_eia861_utility_data` table contains boolean values for an array of different NERC regions. Technically, the raw table's primary key is `[report_date, utility_id_eia, state]`, but with 88888 values we get duplicates with slightly different data: 

(copied from the raw 2023 data)
<img width="1075" alt="Image" src="https://github.com/user-attachments/assets/c5f0691d-7b46-42a3-8134-7ae3c2f22cc9" />

In this case, option 2 calls for us to aggregate these values into one blob; however, we can't do that with non numeric values.
