### ISSUE TITLE
Refactor ETL settings and validate with Pydantic

### ISSUE THREAD

**Issue by rousik** [catalyst-cooperative/pudl#909]
### Description
Replace our messy, hand-crafted ETL input validation system with a more robust and extensible settings validator using Pydantic.

**Harvest tag:** [etl] ETL Scaling & Automation (Sloan)

### Motivation
Currently, our settings file validation is handled by a bunch of bespoke functions in etl.py. Pydantic makes it easy to extend and test our validation. 

Also, the prefect and metadata lines of work introduce a bunch of new command-line arguments (we're up to 20+). The args are needed in different parts of the code and are being passed around in strange ways: 

```python
# From the prefect branch
def etl(  # noqa: C901
    etl_settings,
    pudl_settings,
    clobber: bool = False,
    use_local_cache: bool = True,
    gcs_cache_path: str = None,
    check_foreign_keys: bool = True,
    check_types: bool = True,
    check_values: bool = True,
    overwrite_ferc1_db=SqliteOverwriteMode.ALWAYS,
    commandline_args: argparse.Namespace = None
):
```
We could consolidate the etl args to something like this:
```python
def etl(
    etl_settings,
    pudl_settings,
    args
)
```
I propose we should include most command line args in our settings file.  This allows us to easily expand the number of command line args in the future. This way our etl arguments can be cleaner:
```python
def etl(etl_settings)
```

### In Scope
- This is epic can be closed when we have a validated settings file that contains datasets and command line args from the current dev branch. 

### Out of Scope
- Merge this work into the prefect branch. 

### Other things to consider
* [ ] Should we integrate application-level settings into this system? Like specifying the location of the raw input datastore, and where the resulting databases and Parquet files should be deposited?
* [ ] What kinds of inputs should be stored in environment variables? Should they also be settable in the file?
* [ ] How do we want to specify analytical output tables that should be generated, post-ETL? Should that information also eventually be stored in this settings file if we're going to integrate those derived outputs into an expanded ETL?
* [ ] Would we want to specify deployment information here too? Like where the Intake Catalog and Datasette outputs should go?

### Useful References
* [Data validation and settings management with Pydantic](https://pydantic-docs.helpmanual.io/usage/settings/)
* [How we validate data using Pydantic](https://datascience.statnett.no/2020/05/11/how-we-validate-data-using-pydantic/)

**Comment by rousik** [comment]
Alternatively, we could use pydantic - https://pydantic-docs.helpmanual.io/

which will take care of turning the yaml files into structured python objects that would be easier to use.

**Comment by zaneselvans** [comment]
@bendnorman I think there might be enough stuff to work on here that it should be an epic rather than an issue.

I think a first cut that just covers the functionality of the existing settings file with basic validation (and adding necessary implicit arguments), such that we can retire the `PUDL_TABLES` and `WORKING_PARTITIONS` dictionaries that are currently in `pudl.constants` would be a great start.

**Comment by bendnorman** [comment]
We are starting this work now because a lot of settings and command line args are being passed around in our dev and prefect branches. The goal is to have one etl_settings object passed from cli.py to etl.py instead of: 

```python
def etl(  # noqa: C901
    etl_settings,
    pudl_settings,
    clobber: bool = False,
    use_local_cache: bool = True,
    gcs_cache_path: str = None,
    check_foreign_keys: bool = True,
    check_types: bool = True,
    check_values: bool = True,
    overwrite_ferc1_db=SqliteOverwriteMode.ALWAYS,
    commandline_args: argparse.Namespace = None
):
```

**Comment by zaneselvans** [comment]
We're doing a bunch of settings validation with Pydantic now, and much of what's discussed here will no longer be relevant with the ETL running in Dagster.
