### ISSUE TITLE
Improve completeness and accuracy of heat rate calculations

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#962]
Our current `heat_rate_by_unit()` calculation only works for generation units with a `unit_id_pudl` which excludes many combined cycle generators. It also doesn't account for combined heat and power plants, in which some fuel consumption is for process heat, not electricity generation.  There are also a variety of outlying values due to parasitic loads or possible reporting errors. Some of these issues can be addressed, improving our estimates. Plausible values can also be assigned where the real value is unfixable, providing a more complete (if estimated) heat rate dataset.

## Tasks
* [ ] Integrate combined-cycle unit ID assignment into the BGA process.
* [ ] Calculate per-unit heat rates based on fuel consumption reported in `boiler_fuel` and electricity output from `generation` tables.
* [ ] Calculate per-plant-primemover heat rates based on generation and fuel for electricity from `generation_fuel` table.
* [ ] Compare resulting heat rates by plant-primemover for cases in which generators are associated with CHP, and cases where they are not, to see how big the impacts are.

## Metrics
* On a per year, and per prime mover basis:
  * What fraction of generators have a `unit_id_pudl` associated with them?
  * What fraction of generator capacity has a `unit_id_pudl` associated with it?
  * What fraction of generation-by-generator has a `unit_id_pudl associated with it?
* For each of generation-by-unit and generation-by-plant-primemover
  * What proportion of overall generation has a heat rate associated with it?
  * What fraction of those heat rates are outside of a reasonable range of values, given the prime-mover / technology type?

## Potential improvements
* If total fuel consumed and net generation are the same on a plant-primemover basis in the `generation_fuel` table and the `generation` / `boiler_fuel` table (by generation unit) does that mean that all generators are accounted for in the `generation` table?
* How can we take the ratio between total and for-electricity fuel consumption on a plant-prime-fuel basis in the `generation_fuel` table and use it to adjust the per-unit heat rates?
