### ISSUE TITLE
Enumerate new kinds of PUDL Unit IDs

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#973]
Right now all of our `unit_id_pudl` values are defined in the context of the boiler generation association. Each row is full association including `(plant_id_eia, generator_id, boiler_id, unit_id_pudl)`. We need to explore the generators which are showing up without PUDL Unit IDs right now, and identify new ways to assign Unit IDs that are meaningful and useful in the context of calculating net generation, fuel consumption, and heat rates.

### Where should we store Unit IDs?
* Currently `unit_id_pudl` is defined by the `boiler_generator_assn` table, with each record containing `[plant_id_eia, generator_id, boiler_id, unit_id_pudl]` but if we have Units that don't involve both boilers and generators, or that are defined in terms of plant+prime mover groups, then the BGA table isn't an appropriate home for the Unit IDs any more.
* A more general `units_pudl` table would have rows at least a primary key composed of `plant_id_eia` and `unit_id_pudl` along with some other columns describing the subset of a plant that is to be associated with the `unit_id_pudl`. But if there are several different ways of slicing the plant, different rows will have NA values in different columns, and NA can't be part of the primary key.
* This isn't just a mechanical issue of how we construct a table (we could create an auto-incrementing pseudo key) but indicates a fuzziness in the definition of our database relations.
* The `generators_eia860` table is pretty exhaustive. Probably anything that we're interested in which is putting out electricity will be in there.
* The `generation_fuel` table also seems to be pretty exhaustive -- it has much more fuel consumption and electricity generation within it -- including fuel for CHP -- than the `boiler_fuel` and `generation` tables.
* Any generator that *does* have a unit 
* It seems like the real defining attributes of a "Unit" are the availability of fuel consumption and electricity generation that correspond to each other, and there are several different ways to get those values out of the data we have.

### Different kinds of generation units:
* BGA (boiler-generator) units, described by `[plant_id_eia, generator_id, boiler_id, unit_id_pudl]` where the generation comes from the `generation_eia923` table and fuel consumption comes from the `boiler_fuel_eia923` table.
* boilerless combined cycle units which are a collection of `[plant_id_eia, generator_id]` tuples, whose generation comes from the `generation_eia923` table and fuel consumption comes from ????? (need to look at where we get the CC generation that we've got now)
* `plant-prime` units, that are defined by the fuel consumption and net generation listed in the `generation_fuel_eia923` table. `plant-prime` units can also be associated with individual generator IDs, since the generators have prime movers associated with them in the generator table. Those generators may also be associated with traditional BGA units, or boilerless CC units. Should be possible to list all generators associated with a `plant-prime` unit, and then subtract all of the generation / fuel explicitly associated with those generators which are part of BGA/boilerless units from the generation_fuel `plant-prime` totals, and estimate the allocation of remaining fuel and generation among the remaining generators associated with that `plant-prime` combo.
* Units based on `plant-prime` will need to think about...
  * steam + combustion turbine parts of combined cycle plants
  * single-shaft combined cycle
  * standalone steam turbines (nuclear vs. fossil)
  * internal combustion
* `plant-prime-fuel` is the finest breakdown available within the `generation_fuel_eia923` table. But it's not directly available on the basis of generators, which record their primary, secondary, tertiary, etc. "energy sources" but don't say anything about the relative proportions of them. Sometimes the primary fuel source changes from year to year as well.

### Tasks:
* [ ] Figure out where (if anywhere) we are getting current CCGT fuel consumption from.
* [ ] Enumerate the boilerless CCGT units and figure out a way to give them a unit ID that's useful alongside the BGA unit IDs.
* [ ] Characterize the population of generators that don't have Unit IDs. What kinds of generators are we currently failing to categorize? How are they different from the ones that we do assign Unit IDs to already?
* [ ] How dominant are different fuels when looking at fuel consumption for electricity and net generation on a plant-prime-fuel basis in the `generation_fuel_eia923` table?
